const stage=document.getElementById('stage');
const frame=document.getElementById('page');
const hud=document.getElementById('device-hud');
const hudDetail=document.getElementById('device-hud-detail');
const routes={order:'pages/order/index.html',checkout:'pages/checkout/index.html',orders:'pages/orders/index.html',dine:'pages/dine/index.html',soldout:'pages/soldout/index.html',more:'pages/more/index.html'};
const BUILD='smt-t2s-1280x800-rebuild.27';
const TARGET_WIDTH=1280;
const TARGET_HEIGHT=800;
let current='';
let childReady=false;
function viewportSize(){const viewport=window.visualViewport;return{width:Math.round(viewport?.width||window.innerWidth),height:Math.round(viewport?.height||window.innerHeight)};}
function isExactTarget(size){return size.width===TARGET_WIDTH&&size.height===TARGET_HEIGHT;}
function applyT2SViewport(){const size=viewportSize();const orientation=size.width>=size.height?'橫屏':'直屏';document.documentElement.dataset.orientation=orientation==='橫屏'?'landscape':'portrait';const exact=isExactTarget(size);const scale=exact?1:Math.min(size.width/TARGET_WIDTH,size.height/TARGET_HEIGHT);const renderedWidth=Math.round(TARGET_WIDTH*scale),renderedHeight=Math.round(TARGET_HEIGHT*scale);stage.style.width=TARGET_WIDTH+'px';stage.style.height=TARGET_HEIGHT+'px';stage.style.left=Math.max(0,Math.round((size.width-renderedWidth)/2))+'px';stage.style.top=Math.max(0,Math.round((size.height-renderedHeight)/2))+'px';stage.style.transform=scale===1?'none':'scale('+scale+')';stage.dataset.profile=exact?'sunmi-t2s-native':'sunmi-t2s-simulator';stage.dataset.viewportWidth=String(size.width);stage.dataset.viewportHeight=String(size.height);stage.dataset.scale=scale.toFixed(4);stage.dataset.fitted='1';document.documentElement.dataset.previewMode=exact?'native':'simulator';if(hud&&hudDetail){hud.hidden=exact;hudDetail.textContent='裝置 '+size.width+'×'+size.height+'（'+orientation+'）｜完整框縮放 '+Math.round(scale*100)+'%｜黃色框內固定為 1280×800｜版本 '+BUILD;}}
function route(){const key=(location.hash.replace(/^#\/?/,'')||'order').split('?')[0];return routes[key]?key:'order';}
function showLoaderError(message){frame.srcdoc='<!doctype html><html lang="zh-HK"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>body{margin:0;display:grid;place-items:center;height:100vh;font-family:-apple-system,BlinkMacSystemFont,"PingFang HK",sans-serif;background:#fff8f3;color:#382b24}.card{max-width:520px;padding:28px;border:1px solid #ead9ce;border-radius:16px;background:#fff;text-align:center}.card strong{display:block;font-size:24px;color:#e84b12;margin-bottom:10px}.card button{min-height:48px;margin-top:12px;padding:0 20px;border:0;border-radius:10px;background:#ef5b23;color:#fff;font-weight:800}</style><body><section class="card"><strong>頁面未能載入</strong><p>'+String(message||'請重新整理後再試')+'</p><button onclick="location.reload()">重新載入</button></section></body></html>';}
function load({force=false}={}){const key=route();if(!force&&key===current)return;current=key;childReady=false;frame.src=routes[key]+'?build='+encodeURIComponent(BUILD);}
frame.addEventListener('error',()=>showLoaderError('子頁載入失敗，資料仍保存在本機。'));
addEventListener('hashchange',()=>load());addEventListener('pageshow',applyT2SViewport);addEventListener('resize',applyT2SViewport,{passive:true});addEventListener('orientationchange',()=>setTimeout(applyT2SViewport,120),{passive:true});
addEventListener('message',event=>{if(event.source!==frame.contentWindow)return;if(event.data?.type==='morefun:page-ready')childReady=true;if(event.data?.type==='morefun:navigate')location.hash='#/'+event.data.route;if(event.data?.type==='morefun:exit-fullscreen'&&document.fullscreenElement)document.exitFullscreen?.();if(event.data?.type==='morefun:set-ui-scale')frame.contentWindow?.postMessage({type:'morefun:ui-scale-disabled',reason:'T2S 使用固定 1280×800 測試框；請使用瀏覽器雙指縮放檢查細節。'},'*');});
applyT2SViewport();load();setTimeout(()=>{if(!childReady)frame.contentWindow?.postMessage({type:'morefun:ping'},'*');},2500);
