
(()=>{const D=window.SMT_DATA;const A=window.SMT_API;const S={page:'dashboard',cart:[],cat:'人氣推薦',orders:[{id:'W1028',source:'網站',total:92,state:'待確認',mins:2},{id:'F2210',source:'Foodpanda',total:68,state:'已接單',mins:9},{id:'P3091',source:'電話',total:123,state:'可取餐',mins:24}],tables:Array.from({length:18},(_,i)=>({n:i+1,state:i%5===0?'paid':i%3===0?'busy':'free',mins:i%3===0?12+i:0,total:i%3===0?55+i*3:0}))};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function scale(){const w=innerWidth,h=innerHeight,k=Math.min(w/1920,h/1080);$('#canvas').style.transform=`translate(-50%,-50%) scale(${k})`;$('#rotateGate').style.display=(h>w&&w<900)?'flex':'none'}addEventListener('resize',scale);addEventListener('orientationchange',()=>setTimeout(scale,120));scale();
function toast(t){const x=$('#toast');x.textContent=t;x.className='toast show';clearTimeout(toast.t);toast.t=setTimeout(()=>x.className='toast',1700)}
function top(){return `<div class="topbar"><div class="brand"><span class="brandmark">磨</span>磨飯 SMT</div><button class="status-pill" data-modal="receive"><i class="dot"></i>接受接單</button><div class="notice">訂單：${S.orders.length}｜待處理 2｜本機模式正常</div><div class="top-actions"><button class="top-action" data-page="incoming">待處理 <span class="badge red">2</span></button><button class="top-action" data-modal="quick">快捷模式</button><button class="top-action" data-page="status">✓ 系統正常</button><button class="top-action" data-modal="display">顯示設定</button></div></div>`}
const nav=[['order','點單'],['orders','訂單'],['dinein','堂食'],['soldout','售罄'],['settings','更多']];function navHtml(){return `<div class="nav">${nav.map(([p,n])=>`<button data-page="${p}" class="${S.page===p?'active':''}">${n}${p==='orders'?'<span class="badge red">3</span>':''}</button>`).join('')}</div>`}
function head(id,title,sub,actions=''){return `<div class="page-head"><div class="page-title"><div class="eyebrow">${id}</div><h1>${title}</h1><p>${sub}</p></div><div class="toolbar">${actions}</div></div>`}
function metric(t,v,s){return `<div class="card metric"><small>${t}</small><strong>${v}</strong><div class="progress"><i style="width:${Math.min(100,parseInt(v)||60)}%"></i></div><small>${s}</small></div>`}
function dashboard(){return `<div class="page">${head('SMT-00','營運總覽','高峰所需資訊集中在一屏','<button class="btn primary" data-page="order">立即點單</button>')}<div class="grid g4">${metric('今日營業額','$6,842','較昨日 +8.4%')}${metric('完成訂單','94','平均客單 $72.8')}${metric('待處理','3','最早等待 9 分鐘')}${metric('打印狀態','100%','5 部打印機在線')}</div><div class="grid split"><div class="card"><h3>即時訂單流</h3><div class="list">${S.orders.map(o=>row(`${o.id}｜${o.source}`,`$${o.total}｜${o.mins}分鐘`,o.state)).join('')}</div></div><div class="card"><h3>今日提醒</h3><div class="list">${row('繁忙時間提示','堂食 35 分鐘紅線','已啟用')}${row('紫米庫存','尚餘約 28 份','注意')}${row('本機備份','10:02 完成','正常')}${row('接單停止時間','今日 19:30','已設定')}</div></div></div></div>`}
function row(a,b,c){return `<div class="row"><div class="row-main"><b>${a}</b><small>${b}</small></div><span class="badge ${c==='正常'||c==='已設定'||c==='可取餐'?'green':c==='注意'||c==='待確認'?'amber':''}">${c}</span></div>`}
function order(){const cats=['人氣推薦','套餐','便當','飯團','小食','飲品'];let ps=D.products.filter(p=>S.cat==='人氣推薦'?['人氣推薦','套餐'].includes(p.cat):p.cat===S.cat);const total=S.cart.reduce((a,x)=>a+x.price*x.qty,0);return `<div class="page order-layout"><div class="card cart"><div><h3>目前訂單</h3><small>現場外賣｜未派流水</small></div><div class="notice">${S.cart.some(x=>x.required)?'待補區｜仍有 Required 未完成｜按商品修改':'Required 已完成，可結帳'}</div><div class="cart-list">${S.cart.length?S.cart.map((x,i)=>`<div class="cart-item ${x.required?'required':''}" data-edit="${i}"><div><b>${x.code} ${x.name}</b><small>${x.required?'尚欠：飲品／飯底':'設定完成'}</small></div><div class="qty"><button data-qty="${i},-1">−</button><b>${x.qty}</b><button data-qty="${i},1">＋</button></div></div>`).join(''):'<div class="notice">尚未加入餐點</div>'}</div><div class="total"><span>合計</span><span>$${total}</span></div><div class="grid g2"><button class="btn" id="hold">${S.cart.length?'掛單':'取單'}</button><button class="btn primary" id="checkout">${S.cart.some(x=>x.required)?'先整理':`結帳 $${total}`}</button></div></div><div class="card catalog"><div class="searchbar"><input id="search" placeholder="搜尋產品名稱／編號"><button class="btn" data-modal="scan">掃碼</button></div><div class="cats">${cats.map(c=>`<button data-cat="${c}" class="${S.cat===c?'active':''}">${c}</button>`).join('')}</div><div class="product-grid">${ps.map((p,i)=>`<button class="product" data-add="${D.products.indexOf(p)}"><span class="code">${p.code}</span><b>${p.name}</b><small>${p.desc}</small><span class="price">$${p.price}</span></button>`).join('')}</div><div class="quick-drinks"><div class="vertical-title">快<br>捷<br>飲<br>品</div>${D.products.filter(p=>p.cat==='飲品').map(p=>`<button class="drink" data-add="${D.products.indexOf(p)}">${p.code} ${p.name}<br>$${p.price}</button>`).join('')}</div></div></div>`}
function product(){return generic('SMT-03','產品設定','Required／套餐 Pool／Link Up','<button class="btn primary" data-modal="product">模擬產品設定</button>',[row('F4 招牌紫米飯團','飯團 Required 1｜飲品選填','完整'),row('A1 紫米 A 餐','飯團 1＋小食 1＋熱飲 1','待補飲品'),row('12 肉燥便當','飯底 Required｜可走蛋','完整'),row('S2 紫米能量餐','Pool 共享選項｜不可重複扣額','完整')],['修改只影響該 CartItem','返回保留分類與捲動位置','跨層雙拼禁止','最便宜合法套餐建議'])}
function checkout(){return generic('SMT-04','結帳','來源、包裝、優惠、付款及備註','<button class="btn success" id="confirmPay">確認收款並成單</button>',[row('訂單來源','現場外賣','可修改'),row('取餐模式','到店自取','已確認'),row('包裝費','$0','獨立顯示'),row('付款方式','現金','待確認')],['備註留空仍可成單','付款與渠道分開','正式確認建立 Idempotency','安全保存完成後才打印'])}
function incoming(){return generic('SMT-05','新 App／Web 訂單','全局提醒、稍後處理與防重複','<button class="btn primary">全部檢視</button>',S.orders.map(o=>row(`${o.id}｜${o.source}`,`$${o.total}｜收到 ${o.mins} 分鐘`,o.state)),['稍後處理保留角標','同一 Submission 不重複成單','接單後才派流水','全頁面都能收到提醒'])}
function orders(){return `<div class="page">${head('SMT-06','訂單','開單 → 完成（可取餐）兩階段','<button class="btn">歷史訂單</button>')}<div class="grid kanban"><div class="kanban-col"><h3>待確認 2</h3><div class="list">${ticket('W1028','網站','$92','2分鐘')}${ticket('WA028','WhatsApp','$144','5分鐘')}</div></div><div class="kanban-col"><h3>已開單 3</h3><div class="list">${ticket('F2210','Foodpanda','$68','9分鐘')}${ticket('P3091','電話','$123','18分鐘')}${ticket('A7712','App','$55','21分鐘')}</div></div><div class="kanban-col"><h3>可取餐 2</h3><div class="list">${ticket('S0922','現場','$76','24分鐘')}${ticket('K8821','Keeta','$108','27分鐘')}</div></div></div></div>`}
function ticket(id,src,total,t){return `<div class="ticket"><div class="row-main"><b>${id}｜${src}</b><small>${t}</small></div><div class="total"><span>${total}</span><button class="btn" data-orderaction="${id}">處理</button></div></div>`}
function dinein(){return `<div class="page">${head('SMT-07','堂食枱面','18 枱共享草稿與 35 分鐘提示','<button class="btn primary" data-page="order">新增堂食</button>')}<div class="grid table-grid scroll">${S.tables.map(t=>`<button class="table-card ${t.state}" data-table="${t.n}"><b>枱 ${t.n}</b><span>${t.state==='free'?'空枱':t.state==='paid'?'已付款待清枱':'用餐中'}</span><small>${t.mins?t.mins+' 分鐘｜$'+t.total:'可開新單'}</small></button>`).join('')}</div></div>`}
function dineinDetail(){return generic('SMT-08','堂食加單／拆帳','同一 Order 內處理所有加單與付款','<button class="btn danger">清枱</button>',[row('主單 T04-20260719','流水 0048｜目前 $168','用餐中'),row('第一輪餐點','$110｜已付款','已付款'),row('第二輪加單','$58｜未付款','待付款'),row('差額處理','$0','正常')],['加單沿用同一 Order','拆帳合計必須相等','付款後改單產生補收／退款','清枱不刪歷史'])}
function soldout(){return `<div class="page">${head('SMT-09','售罄／暫停','單選、多選、搜尋與快速恢復','<button class="btn success" id="restore">恢復今日售罄</button>')}<div class="grid split"><div class="card"><h3>產品供應</h3><div class="searchbar"><input placeholder="搜尋產品"><button class="btn">多選</button></div><div class="list" style="margin-top:12px">${D.products.map((p,i)=>`<div class="row"><div class="row-main"><b>${p.code} ${p.name}</b><small>${p.cat}｜$${p.price}</small></div><button class="btn ${i%5===0?'danger':''}" data-sold="${i}">${i%5===0?'恢復':'設為售罄'}</button></div>`).join('')}</div></div><div class="card"><h3>快速控制</h3><div class="list">${row('紫米專用售罄','只影響紫米相關產品','可執行')}${row('今日售罄','05:00 自動恢復','已啟用')}${row('永久停止','必須手動恢復','0 項')}${row('同步狀態','前端副本延遲 2 秒','正常')}</div></div></div></div>`}
function printing(){return generic('SMT-10','打印控制','後廚×2、標籤×2、收據×1','<button class="btn primary" data-modal="print">打印測試頁</button>',[row('Sunmi T2s 內置收據','192.168.1.20｜Ready','正常'),row('XP-N160II 後廚 A','192.168.1.31｜Queue 0','正常'),row('XP-N160II 後廚 B','192.168.1.32｜Queue 1','注意'),row('T271U 標籤 A／B','Queue 0｜網口','正常')],['Print Job 去重','補印清晰標示','打印異常不阻止安全成單','飯團必須打印標籤'])}
function aftersales(){return generic('SMT-11','退款／補收／反結帳','所有差額及版本可追溯','<button class="btn primary" data-modal="refund">建立售後事件</button>',[row('O-20260719-0042','原單 $128｜Version 2','可處理'),row('退款事件 R-008','退款 $18｜FPS','已完成'),row('補收事件 C-014','補收 $6｜現金','待確認'),row('跨日歸屬','歸入原營業日','正常')],['原版本不可刪除','售後不重啟30分鐘','差額建立付款事件','所有操作進 Timeline'])}
function dayclose(){return generic('SMT-12','日結','現金核對、支出、差異與本機備份','<button class="btn primary" data-modal="close">開始日結</button>',[row('系統現金','$3,842','待核對'),row('實點現金','$3,840','差異 -$2'),row('今日支出','$260','已記錄'),row('未完成交易','0 單','正常')],['營業日邊界 05:00','差異門檻自動判斷','重開建立新版本','完成後自動本機備份'])}
function reports(){return `<div class="page">${head('SMT-13','報表與歷史','本機即時產生，不等待雲端','<button class="btn">匯出 CSV</button>')}<div class="grid g4">${metric('營業額','$6,842','今日')}${metric('客單價','$72.8','94 單')}${metric('紫米佔比','51%','主要產品線')}${metric('便當佔比','46%','第二產品線')}</div><div class="grid split"><div class="card"><h3>每小時營業額</h3><div class="chart">${[22,46,75,52,88,66,41,28].map((v,i)=>`<div class="bar" style="height:${v*2.1}px"><b>$${v*20}</b></div>`).join('')}</div></div><div class="card"><h3>產品排行</h3><div class="list">${row('F4 招牌紫米飯團','售出 24','第一')}${row('12 肉燥便當','售出 19','第二')}${row('A1 紫米 A 餐','售出 13','第三')}${row('S2 紫米能量餐','售出 9','第四')}</div></div></div></div>`}
function settings(){const cards=[['啟動與裝置','startup'],['產品 Required','product'],['結帳設定','checkout'],['新訂單提醒','incoming'],['堂食加單','dinein-detail'],['打印設備','printing'],['退款補收','aftersales'],['日結','dayclose'],['報表','reports'],['全局狀態','status'],['備份與恢復','backup'],['版本與更新','update']];return `<div class="page">${head('SMT-14','更多／設定','低頻功能集中，避免污染主導航','<button class="btn">搜尋設定</button>')}<div class="grid setting-grid scroll">${cards.map(([n,p],i)=>`<button class="setting-card" data-page="${p}"><span class="badge">${String(i+1).padStart(2,'0')}</span><b>${n}</b><small>進入管理與操作</small></button>`).join('')}</div></div>`}
function status(){return generic('SMT-15','全局狀態中心','API、同步、打印、備份與快速模式','<button class="btn primary" data-modal="quick">調整快速模式</button>',[row('Customer API','延遲 86ms','正常'),row('Staff／Sync API','最後同步 10:18','正常'),row('打印系統','4 正常｜1 注意','注意'),row('本機備份','今日 10:02','正常')],['狀態不互相混淆','異常不造成廣泛鎖機','快速模式全局一致','卡片互動不跳位'])}
function startup(){return generic('SMT-01','啟動與裝置','日常無登入閘門，本機優先載入','<button class="btn primary">重新檢查裝置</button>',[row('裝置 dev-smt-main','Sunmi T2s｜已綁定','正常'),row('Staff Session','morefun｜SMT Scope','正常'),row('本機資料庫','SQLite／Room Ready','正常'),row('網絡狀態','離線仍可營運','正常')],['一次裝置授權','網絡檢查不阻塞','未完成交易不重複成單','Kiosk 退出二次確認'])}
function generic(id,title,sub,actions,rows,points){return `<div class="page">${head(id,title,sub,actions)}<div class="grid split"><div class="card"><h3>目前狀態</h3><div class="list">${rows.join('')}</div></div><div class="card"><h3>核心 Gate</h3><div class="list">${points.map((p,i)=>row(`${i+1}. ${p}`,'已套用至目前操作流程','已鎖定')).join('')}</div></div></div></div>`}
function render(){$('#topbar').innerHTML=top();$('#mainnav').innerHTML=navHtml();const map={dashboard, startup,order,product,checkout,incoming,orders,dinein,'dinein-detail':dineinDetail,soldout,printing,aftersales,dayclose,reports,settings,status,backup:()=>generic('SMT-14','備份與恢復','先驗證，再建立副本，不直接覆蓋唯一資料庫','<button class="btn primary">建立備份</button>',[row('最近備份','2026-07-19 10:02','正常'),row('本機資料庫','248 MB','正常')],['恢復前驗證完整性','恢復至新副本','可回退','記錄操作人']),update:()=>generic('SMT-14','版本與更新','更新失敗自動回退','<button class="btn primary">檢查更新</button>',[row('目前版本','T2 Master V1.0','正常'),row('Service Worker','Build 20260719','正常')],['不強制更新','先下載再切換','健康檢查','失敗回退'])};$('#workspace').innerHTML=(map[S.page]||dashboard)();bind()}
function bind(){$$('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;render()});$$('[data-cat]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;render()});$$('[data-add]').forEach(b=>b.onclick=()=>{const p=D.products[+b.dataset.add],x=S.cart.find(x=>x.code===p.code&&!x.required);if(x)x.qty++;else S.cart.push({...p,qty:1,required:['套餐','便當','飯團'].includes(p.cat)});render();toast(`${p.name} 已加入`)});$$('[data-qty]').forEach(b=>b.onclick=e=>{e.stopPropagation();let[i,d]=b.dataset.qty.split(',').map(Number);S.cart[i].qty+=d;if(S.cart[i].qty<=0)S.cart.splice(i,1);render()});$$('[data-edit]').forEach(b=>b.onclick=()=>{const x=S.cart[+b.dataset.edit];modal('完成 Required',`<p>${x.code} ${x.name}</p><div class="form-grid"><button class="btn">正常飯</button><button class="btn">少飯</button><button class="btn">台式奶茶</button><button class="btn">無需飲品 −$1</button></div><br><button class="btn primary" id="doneReq">確認設定</button>`);setTimeout(()=>$('#doneReq').onclick=()=>{x.required=false;closeModal();render();toast('Required 已完成')},0)});$$('[data-modal]').forEach(b=>b.onclick=()=>modal('操作設定',`<p>此設定會沿用 T2 橫屏工作流程。</p><div class="list">${row('目前狀態','本機設定已載入','正常')}${row('套用範圍','全局／目前裝置','可修改')}</div>`));$$('[data-table]').forEach(b=>b.onclick=()=>{S.page='dinein-detail';render()});$$('[data-orderaction]').forEach(b=>b.onclick=()=>modal('訂單處理',`<p>${b.dataset.orderaction}</p><div class="grid g2"><button class="btn">稍後處理</button><button class="btn primary" id="acceptOrder">接單並開單</button></div>`));const co=$('#checkout');if(co)co.onclick=()=>{if(S.cart.some(x=>x.required))toast('請先完成 Required');else{S.page='checkout';render()}};const hp=$('#hold');if(hp)hp.onclick=()=>toast(S.cart.length?'訂單已掛起':'已打開取單列表');const cp=$('#confirmPay');if(cp)cp.onclick=()=>{toast('已安全成單並建立打印 Job');S.cart=[];S.page='orders';setTimeout(render,600)};$$('[data-sold]').forEach(b=>b.onclick=()=>{b.textContent=b.textContent==='設為售罄'?'恢復':'設為售罄';toast('供應狀態已更新')})}
function modal(title,body){$('#modalRoot').innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="page-head"><h2>${title}</h2><button class="btn" id="closeModal">關閉</button></div>${body}</div></div>`;$('#closeModal').onclick=closeModal;$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))closeModal()}}function closeModal(){$('#modalRoot').innerHTML=''}
render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
})();
