import {createInitialDineState,tableView,openTable,acceptQrSubmission,applyFullPayment,applyItemPayment} from './dine-domain.js';
import {ORDER_STORAGE_KEY,DRAFT_STORAGE_KEY,DINE_STORAGE_KEY,readJSON,writeJSON} from '../../shared/store.js';

const app=document.getElementById('app');
const KEY=DINE_STORAGE_KEY;
const money=value=>`$${Number(value||0).toFixed(0)}`;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const paymentMethods=['現金','轉數快','PayMe','支付寶','微信支付','組合付款'];

function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved?.tables?.length!==9)return createInitialDineState();saved.tables=saved.tables.map(table=>({...table,session:table.session?{items:[],orderBatches:[],pendingSubmissions:[],payments:[],...table.session}:null}));saved.waiting=Array.isArray(saved.waiting)?saved.waiting:[];return saved;}catch{return createInitialDineState();}}
let state=load(),panel=null,selectedItems={},notice='';
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const selectedTable=()=>{const selected=state.tables.find(table=>table.id===state.selectedTableId);return selected?.joinedTo?state.tables.find(table=>table.id===selected.joinedTo)||selected:selected;};
const view=table=>tableView(table,Date.now());
const tableDrafts=table=>(readJSON(DRAFT_STORAGE_KEY,[])||[]).filter(draft=>draft.context?.mode==='dine'&&draft.context.tableId===table.id&&(!draft.context.sessionId||draft.context.sessionId===table.session?.id));
function startTableOrder(table){
  const index=state.tables.findIndex(entry=>entry.id===table.id);
  if(table.status!=='occupied'){state.tables[index]=openTable(table);table=state.tables[index];}
  writeJSON(ORDER_STORAGE_KEY,{cart:[],category:'全部',draftSession:null,dineContext:{mode:'dine',tableId:table.id,sessionId:table.session.id}});
  save();navigate('order');
}

function topbar(){const occupied=state.tables.filter(t=>t.status==='occupied').length,pending=state.tables.reduce((n,t)=>n+(t.session?.pendingSubmissions?.length||0),0);return `<header class="topbar"><div class="brand">磨飯 SMT</div><span class="terminal">SMT 主機</span><span class="online">● 系統在線</span><div class="spacer"></div><button class="top-btn" data-action="waiting">輪候 ${state.waiting.length}</button><button class="top-btn ${pending?'attention':''}" data-action="next-pending">待確認 ${pending}</button><span class="summary">使用中 <b>${occupied}</b>／9</span></header>`;}
function waitingBar(){const first=state.waiting[0],minutes=first?Math.floor((Date.now()-first.createdAt)/60_000):0;return `<button class="waiting-bar" data-action="waiting"><span><b>輪候位置</b><small>${state.waiting.length?`${state.waiting.length} 組等候中｜最早 ${minutes} 分鐘`:'暫時無人輪候'}</small></span><strong>查看輪候 ›</strong></button>`;}
function tableCard(table){const x=view(table),draftCount=table.status==='occupied'?tableDrafts(table).length:0,joined=table.joinedTables?.length?`${table.id}＋${table.joinedTables.join('＋')} 拼枱`:table.joinedTo?`與 ${table.joinedTo} 號拼枱`:'';return `<button class="table-card ${x.status} ${x.isLate?'late':''} ${x.pendingCount?'pending':''}" data-action="table" data-id="${esc(table.id)}"><header><strong>${table.id==='戶外'?'戶外枱':`${table.id} 號枱`}</strong>${x.pendingCount?`<em>${x.pendingCount} 待確認</em>`:draftCount?`<em>${draftCount} 張暫存</em>`:''}</header><div class="table-state"><b>${x.status==='free'?'未使用':'使用中'}</b>${x.status==='occupied'?`<span>${x.minutes} 分鐘</span>`:''}</div>${x.status==='occupied'?`<footer><span>${joined||`未付 ${money(x.unpaid)}`}</span>${x.isLate?'<strong>已滿35分鐘</strong>':''}</footer>`:'<footer><span>撳入直接點餐</span></footer>'}</button>`;}
function main(){return `<main class="app">${topbar()}<section class="workspace dine-workspace"><section class="dine-main">${waitingBar()}<div class="table-grid">${state.tables.map(tableCard).join('')}</div></section>${detailPanel()}</section><nav class="bottom-nav"><button data-action="navigate-order">點餐</button><button data-action="navigate-orders">訂單</button><button class="active">堂食</button><button>售罄</button><button>更多</button></nav></main>${overlay()}<div class="toast ${notice?'show':''}">${esc(notice)}</div>`;}
function detailPanel(){const table=selectedTable();if(!table)return `<aside class="table-detail empty-detail"><div><b>堂食枱面</b><p>撳枱卡直接開枱點餐，或查看使用中枱位。</p></div></aside>`;const x=view(table);if(x.status==='free')return `<aside class="table-detail"><header><div><small>未使用</small><h1>${esc(table.id)}${table.id==='戶外'?'枱':' 號枱'}</h1></div><button data-action="close-detail">×</button></header><div class="empty-table"><b>此枱可以使用</b><p>毋須再選枱號，直接開始點餐。</p></div><footer><button class="primary" data-action="open-and-order">開始點餐</button></footer></aside>`;const s=table.session||{},batches=s.orderBatches||[],pending=s.pendingSubmissions||[],draftsForTable=tableDrafts(table),lastBatch=batches.at(-1),lastPayment=(s.payments||[]).at(-1),opened=new Date(table.openedAt).toLocaleTimeString('zh-HK',{hour:'2-digit',minute:'2-digit'});return `<aside class="table-detail"><header><div><small>${opened} 開枱｜已用 ${x.minutes} 分鐘${x.isLate?'｜請留意用枱情況':''}</small><h1>${esc(table.id)}${table.id==='戶外'?'枱':' 號枱'}</h1></div><button data-action="close-detail">×</button></header><section class="amount-strip"><span>總額<b>${money(x.total)}</b></span><span>已付<b>${money(x.paid)}</b></span><span>未付<b>${money(x.unpaid)}</b></span></section>${draftsForTable.length?`<button class="pending-callout" data-action="continue-draft"><span><b>有 ${draftsForTable.length} 張暫存單</b><small>屬於此枱，尚未正式落單</small></span><strong>繼續點餐</strong></button>`:''}${pending.length?`<button class="pending-callout" data-action="review-pending" data-id="${pending[0].id}"><span><b>有 ${pending.length} 張掃碼落單待確認</b><small>第二版保留入口，暫未接入正式堂食流程</small></span><strong>查看</strong></button>`:''}<section class="batch-summary"><header><b>最近落單</b><button data-action="records">查看全部</button></header><p>${lastBatch?`${new Date(lastBatch.createdAt).toLocaleTimeString('zh-HK',{hour:'2-digit',minute:'2-digit'})}｜${lastBatch.items.map(item=>`${esc(item.name)} ×${item.qty}`).join('、')}｜${money(lastBatch.items.reduce((n,item)=>n+item.unitPrice*item.qty,0))}`:'開枱後尚未正式落單'}</p></section><section class="batch-summary"><header><b>最近付款</b></header><p>${lastPayment?`${new Date(lastPayment.createdAt).toLocaleTimeString('zh-HK',{hour:'2-digit',minute:'2-digit'})}｜${esc(lastPayment.method)} ${money(lastPayment.amount)}｜尚欠 ${money(x.unpaid)}`:'尚未有付款記錄'}</p></section><div class="primary-actions"><button class="primary" data-action="add-order">加單</button><button data-action="payment" ${x.unpaid>0?'':'disabled'}>付款</button><button data-action="records">訂單記錄</button><button data-action="more">更多</button></div></aside>`;}
function overlay(){if(!panel)return '';if(panel==='waiting')return drawer('輪候位置',`<div class="waiting-list">${state.waiting.map(w=>`<article><span><b>${esc(w.id)}｜${esc(w.name)}</b><small>已等候 ${Math.floor((Date.now()-w.createdAt)/60_000)} 分鐘${w.hasOrder?'｜已預先落單':''}</small></span><button data-action="seat-waiting" data-id="${w.id}">安排入座</button></article>`).join('')||'<p>暫時無人輪候</p>'}</div>`,`<button data-action="close-panel">返回</button><button class="primary" data-action="new-waiting">＋ 建立輪候</button>`);
if(panel==='more')return drawer('更多操作',`<div class="action-list"><button data-action="permanent-qr">永久枱碼<small>第二版保留入口，暫未接入點餐</small></button><button data-action="session-qr">即時枱碼<small>第二版保留入口，暫未接入點餐</small></button><button>轉枱</button><button>拼枱／拆枱</button><button data-action="records">重印／訂單記錄</button><button class="danger-text" data-action="end-table">結束用枱</button></div>`,`<button data-action="close-panel">返回</button>`);
if(panel==='records'){const t=selectedTable(),s=t.session||{};return drawer(`${t.id} 號枱｜訂單記錄`,`<div class="record-list">${(s.items||[]).map((item,i)=>`<article><b>${i+1}. ${esc(item.name)} ×${item.qty}</b><span>${money(item.unitPrice*item.qty)}｜已付 ${item.paidQty||0}</span></article>`).join('')||'<p>尚未有餐品</p>'}${(s.payments||[]).map(p=>`<article class="payment-record"><b>${esc(p.method)}｜${money(p.amount)}</b><span>付款批次 ${esc(p.id)}</span></article>`).join('')}</div>`,`<button data-action="close-panel">返回</button><button data-action="reprint">重印訂單</button>`);}
if(panel==='payment')return paymentChoice();if(panel==='item-payment')return itemPayment();if(panel==='payment-method')return paymentMethod();if(panel==='pending')return pendingReview();if(panel?.startsWith('qr:'))return qrPanel(panel.slice(3));return ''}
function drawer(title,body,footer){return `<div class="overlay-scrim"><aside class="side-panel"><header><h2>${title}</h2><button data-action="close-panel">×</button></header><div class="panel-body">${body}</div><footer>${footer}</footer></aside></div>`;}
function paymentChoice(){const x=view(selectedTable());return drawer('付款',`<p class="panel-lead">先選擇今次付款範圍；付款餐品明細會逐項鎖定。</p><div class="choice-cards"><button data-action="full-payment"><b>全數付款</b><small>一次收取尚欠 ${money(x.unpaid)}</small></button><button data-action="item-payment"><b>選擇餐品付款</b><small>按餐品及數量分拆多人付款</small></button></div>`,`<button data-action="close-panel">返回</button>`);}
function itemPayment(){const items=selectedTable().session.items||[];return drawer('選擇餐品付款',`<div class="payment-items">${items.map((item,index)=>{const unpaid=item.qty-(item.paidQty||0),selected=selectedItems[item.lineId]||0;return `<article class="${unpaid?'':'paid'}"><span><b>${index+1}. ${esc(item.name)}</b><small>${money(item.unitPrice)}｜未付 ${unpaid}／${item.qty}</small></span>${unpaid?`<div class="qty-picker"><button data-action="pay-qty" data-id="${item.lineId}" data-delta="-1">−</button><b>${selected}</b><button data-action="pay-qty" data-id="${item.lineId}" data-delta="1">＋</button></div>`:'<em>已付</em>'}</article>`}).join('')}</div>`,`<button data-action="payment">返回</button><button class="primary" data-action="choose-method" ${Object.values(selectedItems).some(Boolean)?'':'disabled'}>下一步</button>`);}
function paymentMethod(){const t=selectedTable(),items=t.session.items||[],amount=Object.entries(selectedItems).reduce((sum,[id,qty])=>sum+(items.find(i=>i.lineId===id)?.unitPrice||0)*qty,0);return drawer('選擇付款方式',`<div class="pay-total"><small>今次應付</small><b>${money(amount)}</b></div><div class="method-grid">${paymentMethods.map(method=>`<button data-action="confirm-payment" data-method="${method}">${method}</button>`).join('')}</div>`,`<button data-action="item-payment">返回選餐品</button>`);}
function pendingReview(){const table=selectedTable(),submission=table?.session?.pendingSubmissions?.[0];if(!submission)return '';const old=view(table).unpaid,add=submission.items.reduce((n,i)=>n+i.qty*i.unitPrice,0);return `<div class="overlay-scrim pending-layer"><aside class="pending-review-panel"><header><div><small>掃碼新增落單｜${esc(table.id)} 號枱</small><h2>請核對今次新增餐品</h2></div><button data-action="close-panel">×</button></header><div class="pending-meta"><span>送出時間<b>${new Date(submission.createdAt).toLocaleTimeString('zh-HK',{hour:'2-digit',minute:'2-digit'})}</b></span><span>新增<b>${money(add)}</b></span><span>確認後未付<b>${money(old+add)}</b></span></div><div class="pending-lines">${submission.items.map((item,i)=>`<article><b>${i+1}</b><span><strong>${esc(item.name)} ×${item.qty}</strong><small>${esc(item.options||'標準配置')}</small></span><em>${money(item.qty*item.unitPrice)}</em></article>`).join('')}</div><footer><button class="danger-text" data-action="reject-pending">拒絕</button><button data-action="edit-pending">修改</button><button class="primary" data-action="accept-pending" data-id="${submission.id}">確認落單</button></footer></aside></div>`;}
function qrPanel(type){const table=selectedTable(),permanent=type==='permanent',value=permanent?`https://order.morefun.hk/dine/table/${encodeURIComponent(table.id)}`:`https://order.morefun.hk/dine/session/${encodeURIComponent(table.session?.id||'')}`;return drawer(permanent?'永久枱碼':'即時枱碼',`<div class="qr-view"><div data-qr="${esc(value)}"></div><b>${esc(table.id)} 號枱</b><p>${permanent?'固定對應此枱，可打印貼於枱面。':'只限今次用枱，結束用枱後失效。'}</p></div>`,`<button data-action="close-panel">返回</button><button data-action="print-qr">打印枱碼</button><button class="primary" data-action="fullscreen-qr">全屏展示</button>`);}
function render(){app.innerHTML=main();save();document.querySelectorAll('[data-qr]').forEach(node=>{if(typeof window.qrcode!=='function')return;const qr=window.qrcode(0,'M');qr.addData(node.dataset.qr);qr.make();node.innerHTML=qr.createImgTag(7,8,'枱號 QR Code')});if(notice)setTimeout(()=>{notice='';render()},1800)}
function navigate(route){window.parent?.postMessage?.({type:'morefun:navigate',route},'*')}
function handle(button){const action=button.dataset.action,table=selectedTable();if(action==='table'){state.selectedTableId=button.dataset.id;panel=null}else if(action==='close-detail')state.selectedTableId=null;else if(action==='open-and-order'||action==='add-order')startTableOrder(table);else if(action==='continue-draft'){writeJSON(ORDER_STORAGE_KEY,{cart:[],category:'全部',draftSession:null,dineContext:{mode:'dine',tableId:table.id,sessionId:table.session.id}});navigate('order')}else if(action==='navigate-order')navigate('order');else if(action==='navigate-orders')navigate('orders');else if(action==='waiting')panel='waiting';else if(action==='next-pending'){const t=state.tables.find(t=>t.session?.pendingSubmissions?.length);if(t){state.selectedTableId=t.id;panel='pending'}}else if(action==='review-pending')panel='pending';else if(action==='accept-pending'){table.session=acceptQrSubmission(table.session,button.dataset.id);panel=null;notice='已確認落單，已加入打印流程'}else if(action==='reject-pending'){table.session.pendingSubmissions.shift();panel=null;notice='已拒絕今次掃碼落單'}else if(action==='edit-pending')notice='修改會接入現有點單編輯器';else if(action==='payment')panel='payment';else if(action==='full-payment'){selectedItems=Object.fromEntries((table.session.items||[]).map(i=>[i.lineId,i.qty-(i.paidQty||0)]).filter(([,q])=>q>0));panel='payment-method'}else if(action==='item-payment'){selectedItems=panel==='payment'?{}:selectedItems;panel='item-payment'}else if(action==='pay-qty'){const item=table.session.items.find(i=>i.lineId===button.dataset.id),max=item.qty-(item.paidQty||0),next=Math.max(0,Math.min(max,(selectedItems[item.lineId]||0)+Number(button.dataset.delta)));selectedItems={...selectedItems,[item.lineId]:next}}else if(action==='choose-method')panel='payment-method';else if(action==='confirm-payment'){const selections=Object.entries(selectedItems).filter(([,qty])=>qty>0).map(([lineId,qty])=>({lineId,qty}));table.session=applyItemPayment(table.session,selections,button.dataset.method);selectedItems={};panel=null;notice=`已記錄${button.dataset.method}付款`;}else if(action==='records')panel='records';else if(action==='more')panel='more';else if(action==='permanent-qr')panel='qr:permanent';else if(action==='session-qr')panel='qr:session';else if(action==='end-table'){const x=view(table);if(x.unpaid>0||tableDrafts(table).length||table.session?.pendingSubmissions?.length){notice='尚有未付、暫存或待確認內容，不可結束用枱';panel=null}else{const index=state.tables.findIndex(t=>t.id===table.id);state.tables[index]={id:table.id,status:'free',openedAt:null,session:null};state.selectedTableId=null;panel=null;notice='已結束用枱'}}else if(action==='close-panel')panel=null;else if(action==='new-waiting')notice='建立輪候表單將於下一階段接入';else if(action==='seat-waiting')notice='請先撳一張未使用枱安排入座';else if(action==='reprint'||action==='print-qr')notice='已加入打印接口隊列（硬件尚未接通）';else if(action==='fullscreen-qr')document.querySelector('.qr-view')?.requestFullscreen?.();render()}
app.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button&&!button.disabled)handle(button)});
render();setInterval(()=>render(),60_000);
