import {ORDER_HISTORY_STORAGE_KEY,ORDER_STORAGE_KEY,TERMINAL_ID_STORAGE_KEY,readJSON,writeJSON} from '../../shared/store.js';
import {normalizeTerminalId} from '../../shared/operations.js';
import {money,escapeHtml} from '../../shared/components.js';
const app=document.getElementById('app'),terminalId=normalizeTerminalId(localStorage.getItem(TERMINAL_ID_STORAGE_KEY)||'SMT'),now=Date.now();
const demo=[
{id:'P0053',group:'onsite',source:'現場外賣',acceptedAt:now-19*60000,itemCount:2,amount:88,paymentMethod:'現金',paymentStatus:'已付款',printStatus:'正常',items:[{name:'招牌牛肉滑蛋飯',qty:1,total:70},{name:'凍檸茶',qty:1,total:18}]},
{id:'P0057',group:'onsite',source:'堂食',acceptedAt:now-16*60000,itemCount:2,amount:92,paymentMethod:'FPS',paymentStatus:'已付款',printStatus:'正常',items:[{name:'鮮茄雞扒飯',qty:1,total:74},{name:'熱咖啡',qty:1,total:18}]},
{id:'P0051',group:'owned',source:'磨飯 App',acceptedAt:now-20*60000,itemCount:2,amount:86,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'正常',items:[{name:'紫米飯團套餐',qty:1,total:59},{name:'小食',qty:1,total:27}]},
{id:'P0054',group:'owned',source:'電話／WhatsApp',acceptedAt:now-11*60000,itemCount:2,amount:76,paymentMethod:'PayMe',paymentStatus:'付款待核實',printStatus:'正常',items:[{name:'叉燒飯',qty:1,total:58},{name:'凍檸茶（少甜）',qty:1,total:18}]},
{id:'P0059',group:'platform',source:'Keeta',acceptedAt:now-18*60000,itemCount:2,amount:90,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'異常',items:[{name:'自選便當',qty:1,total:72},{name:'飲品',qty:1,total:18}]},
{id:'P0060',group:'platform',source:'Foodpanda',acceptedAt:now-12*60000,itemCount:2,amount:82,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'正常',items:[{name:'飯團套餐',qty:1,total:64},{name:'飲品',qty:1,total:18}]}];
let orders=readJSON(ORDER_HISTORY_STORAGE_KEY,[]);if(!orders.length)orders=demo;let selectedId=orders[0]?.id||'',modal='';const groups=[['onsite','現場'],['owned','自有渠道'],['platform','外賣平台']];
const minutes=o=>Math.max(0,Math.floor((Date.now()-Number(o.acceptedAt||Date.now()))/60000));
function orderCard(o){return '<button class="order-card '+(selectedId===o.id?'selected':'')+'" data-action="select-order" data-id="'+o.id+'"><header><span><small>'+escapeHtml(o.source)+'</small><strong>'+escapeHtml(o.id)+'</strong></span><b>'+minutes(o)+'分鐘</b></header><div><span>'+o.itemCount+' 件</span><strong>'+money(o.amount)+'</strong></div><footer><span>'+escapeHtml(o.paymentMethod)+'</span><span class="'+(o.printStatus==='異常'?'bad':'ok')+'">打印'+escapeHtml(o.printStatus)+'</span></footer></button>';}
function lane(key,title){const rows=orders.filter(o=>o.group===key).sort((a,b)=>Number(b.acceptedAt)-Number(a.acceptedAt));return '<section class="lane"><header><div><strong>'+title+'</strong><small>進行中 '+rows.length+' ｜ 異常 '+rows.filter(o=>o.printStatus==='異常'||o.paymentStatus.includes('待')).length+'</small></div><b>'+money(rows.reduce((n,o)=>n+Number(o.amount||0),0))+'</b></header><div class="lane-scroll">'+rows.map(orderCard).join('')+'</div></section>';}
function detail(){const o=orders.find(x=>x.id===selectedId);if(!o)return '<aside class="detail empty">未有訂單</aside>';return '<aside class="detail"><header><div><small>'+escapeHtml(o.source)+'</small><h2>'+escapeHtml(o.id)+'</h2></div><span>'+minutes(o)+' 分鐘</span></header><div class="meta"><span>付款方式<b>'+escapeHtml(o.paymentMethod)+'</b></span><span>付款狀態<b>'+escapeHtml(o.paymentStatus)+'</b></span><span>操作終端<b>'+escapeHtml(o.checkoutTerminalId||'待同步')+'</b></span></div><div class="items">'+(o.items||[]).map(x=>'<article><span>'+escapeHtml(x.name)+' ×'+x.qty+'</span><b>'+money(x.total)+'</b></article>').join('')+'</div><div class="total"><span>訂單總額</span><b>'+money(o.amount)+'</b></div><div class="detail-actions"><button data-action="change-payment">換渠道／付款方式</button><button data-action="reprint">重印</button><button data-action="partial-cancel">部分取消</button><button class="danger" data-action="reverse-open">反結帳</button></div></aside>';}
function reverseModal(){const o=orders.find(x=>x.id===selectedId);return '<div class="scrim"></div><section class="reverse-card"><header><div><small>訂單 '+escapeHtml(o.id)+'</small><strong>反結帳</strong></div><button data-action="close-modal">×</button></header><button class="choice danger" data-action="cancel-order"><strong>整單取消</strong><span>取消整張訂單，不重用內容；不打印</span></button><button class="choice" data-action="reuse-order"><strong>反結帳並重用</strong><span>原有商品載入點單頁，可刪除、修改及新增；此步不打印</span></button><footer><button data-action="close-modal">返回</button></footer></section>';}
function render(){const p=orders.filter(o=>o.paymentStatus.includes('待')).length,b=orders.filter(o=>o.printStatus==='異常').length,last=orders.filter(o=>minutes(o)>=25).length;app.innerHTML='<main><header class="topbar"><div class="brand">磨飯 SMT</div><span class="terminal">'+terminalId+'</span><span class="online">● 接單中</span><div class="spacer"></div><button>待處理 5</button><button>快捷 ON</button><button>設備 3</button></header><section class="workspace"><header class="page-head"><div><h1>訂單</h1><p>接受後成為運行中訂單，30分鐘後自動完成。</p></div><button>來源：全部</button><button>付款待核實</button><button>打印異常</button></header><section class="stats"><article>進行中訂單<b>'+orders.length+'</b></article><article>付款待核實<b>'+p+'</b></article><article>打印異常<b>'+b+'</b></article><article>最後5分鐘<b>'+last+'</b></article></section><section class="orders-layout">'+detail()+'<div class="lanes">'+groups.map(g=>lane(...g)).join('')+'</div></section></section><nav class="bottom-nav"><button data-action="navigate-order">點餐</button><button class="active">訂單</button><button>堂食</button><button>售罄</button><button>更多</button></nav></main>'+(modal==='reverse'?reverseModal():'')+'<div id="toast" class="toast"></div>';}
function toast(t){const n=document.getElementById('toast');n.textContent=t;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),1400);}
function handle(b){const a=b.dataset.action;if(a==='select-order'){selectedId=b.dataset.id;render();}else if(a==='navigate-order')parent.postMessage({type:'morefun:navigate',route:'order'},'*');else if(a==='reverse-open'){modal='reverse';render();}else if(a==='close-modal'){modal='';render();}else if(a==='cancel-order'){orders=orders.filter(o=>o.id!==selectedId);writeJSON(ORDER_HISTORY_STORAGE_KEY,orders);selectedId=orders[0]?.id||'';modal='';render();toast('整張訂單已取消');}else if(a==='reuse-order'){const o=orders.find(x=>x.id===selectedId);writeJSON(ORDER_STORAGE_KEY,{cart:(o.items||[]).map((x,i)=>({lineId:'reuse-'+o.id+'-'+i,productId:x.productId||'',name:x.name,image:x.image||'',qty:x.qty||1,unitPrice:Number(x.total||0)/Math.max(1,x.qty||1),total:Number(x.total||0),options:x.options||{},required:[],drinkSlots:0,drinkAssignments:[],createdOrder:i})),reuse:{orderId:o.id,startedByTerminalId:terminalId,startedAt:Date.now()},category:'全部'});parent.postMessage({type:'morefun:navigate',route:'order'},'*');}else if(a==='change-payment')toast('已開啟渠道／付款方式');else if(a==='reprint')toast('已開啟分類重印');else if(a==='partial-cancel')toast('已開啟部分取消');}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handle(b);});render();
