import {ORDER_HISTORY_STORAGE_KEY,ORDER_STORAGE_KEY,TERMINAL_ID_STORAGE_KEY,readJSON,writeJSON} from '../../shared/store.js';
import {normalizeTerminalId} from '../../shared/operations.js';
import {money,escapeHtml} from '../../shared/components.js';
import {applyOrderFilters,cancelOrder,changeOrderPayment,partiallyCancelItem,queueReprint,isHistory} from './orders-domain.js';
const app=document.getElementById('app'),terminalId=normalizeTerminalId(localStorage.getItem(TERMINAL_ID_STORAGE_KEY)||'SMT'),now=Date.now();
const demo=[
{id:'P0053',group:'onsite',source:'現場外賣',status:'running',acceptedAt:now-19*60000,itemCount:2,amount:88,paymentMethod:'現金',paymentStatus:'已付款',printStatus:'正常',items:[{name:'招牌牛肉滑蛋飯',qty:1,total:70},{name:'凍檸茶',qty:1,total:18}]},
{id:'P0057',group:'onsite',source:'堂食',status:'running',acceptedAt:now-16*60000,itemCount:2,amount:92,paymentMethod:'FPS',paymentStatus:'已付款',printStatus:'正常',items:[{name:'鮮茄雞扒飯',qty:1,total:74},{name:'熱咖啡',qty:1,total:18}]},
{id:'P0051',group:'owned',source:'磨飯 App',status:'completed',acceptedAt:now-50*60000,itemCount:2,amount:86,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'正常',items:[{name:'紫米飯團套餐',qty:1,total:59},{name:'小食',qty:1,total:27}]},
{id:'P0054',group:'owned',source:'電話／WhatsApp',status:'running',acceptedAt:now-11*60000,itemCount:2,amount:76,paymentMethod:'PayMe',paymentStatus:'付款待核實',printStatus:'正常',items:[{name:'叉燒飯',qty:1,total:58},{name:'凍檸茶（少甜）',qty:1,total:18}]},
{id:'P0059',group:'platform',source:'Keeta',status:'running',acceptedAt:now-18*60000,itemCount:2,amount:90,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'異常',items:[{name:'自選便當',qty:1,total:72},{name:'飲品',qty:1,total:18}]},
{id:'P0060',group:'platform',source:'Foodpanda',status:'running',acceptedAt:now-12*60000,itemCount:2,amount:82,paymentMethod:'平台已付',paymentStatus:'已付款',printStatus:'正常',items:[{name:'飯團套餐',qty:1,total:64},{name:'飲品',qty:1,total:18}]}];
let orders=readJSON(ORDER_HISTORY_STORAGE_KEY,[]);if(!orders.length)orders=demo;
let selectedId='',modal='',notice='',filters={view:'active',source:'all',exception:''};
const groups=[['onsite','現場'],['owned','自有渠道'],['platform','外賣平台']],sources=['堂食','現場外賣','磨飯 App','電話／WhatsApp','Keeta','Foodpanda'],payments=['現金付款','FPS','PayMe','Alipay','WeChat Pay','平台已付','稍後付款'];
const minutes=o=>Math.max(0,Math.floor((Date.now()-Number(o.acceptedAt||Date.now()))/60000));
const visible=()=>applyOrderFilters(orders,filters);
function persist(updated,message){orders=orders.map(o=>o.id===updated.id?updated:o);writeJSON(ORDER_HISTORY_STORAGE_KEY,orders);modal='';notice=message;render();}
function orderCard(o){return '<button class="order-card '+(selectedId===o.id?'selected':'')+'" data-action="select-order" data-id="'+o.id+'"><header><span><small>'+escapeHtml(o.source)+'</small><strong>'+escapeHtml(o.id)+'</strong></span><b>'+(isHistory(o)?statusLabel(o):minutes(o)+'分鐘')+'</b></header><div><span>'+o.itemCount+' 件</span><strong>'+money(o.amount)+'</strong></div><footer><span>'+escapeHtml(o.paymentMethod)+'</span><span class="'+(o.printStatus==='異常'?'bad':'ok')+'">打印'+escapeHtml(o.printStatus)+'</span></footer></button>';}
function statusLabel(o){return o.status==='cancelled'?'已取消':'已完成';}
function lane(key,title){const rows=visible().filter(o=>o.group===key).sort((a,b)=>Number(b.acceptedAt)-Number(a.acceptedAt));return '<section class="lane"><header><div><strong>'+title+'</strong><small>'+ (filters.view==='history'?'歷史':'進行中') +' '+rows.length+' ｜ 異常 '+rows.filter(o=>o.printStatus==='異常'||String(o.paymentStatus).includes('待')).length+'</small></div><b>'+money(rows.reduce((n,o)=>n+Number(o.amount||0),0))+'</b></header><div class="lane-scroll">'+(rows.length?rows.map(orderCard).join(''):'<p class="empty-row">沒有符合條件的訂單</p>')+'</div></section>';}
function detail(){const o=orders.find(x=>x.id===selectedId);if(!o)return '<aside class="detail empty">請選擇一張訂單</aside>';return '<aside class="detail"><header><div><small>'+escapeHtml(o.source)+'</small><h2>'+escapeHtml(o.id)+'</h2></div><span>'+(isHistory(o)?statusLabel(o):minutes(o)+' 分鐘')+'</span></header><div class="meta"><span>付款方式<b>'+escapeHtml(o.paymentMethod)+'</b></span><span>付款狀態<b>'+escapeHtml(o.paymentStatus)+'</b></span><span>操作終端<b>'+escapeHtml(o.checkoutTerminalId||'待同步')+'</b></span></div><div class="items">'+(o.items||[]).map(x=>'<article><span>'+escapeHtml(x.name)+' ×'+x.qty+(x.cancelledQty?' <em>已取消 ×'+x.cancelledQty+'</em>':'')+'</span><b>'+money(x.total)+'</b></article>').join('')+'</div><div class="total"><span>訂單總額</span><b>'+money(o.amount)+'</b></div><div class="detail-actions">'+(isHistory(o)?'<button data-action="timeline">查看操作紀錄</button>':'<button data-action="change-payment">換渠道／付款方式</button><button data-action="reprint">重印</button><button data-action="partial-cancel">部分取消</button><button class="danger" data-action="reverse-open">反結帳</button>')+'</div></aside>';}
const overlay=content=>'<div class="scrim"></div><section class="reverse-card">'+content+'</section>';
function modalHtml(){const o=orders.find(x=>x.id===selectedId);if(!modal||!o)return '';
  const head=t=>'<header><div><small>訂單 '+escapeHtml(o.id)+'</small><strong>'+t+'</strong></div><button data-action="close-modal">×</button></header>';
  if(modal==='reverse')return overlay(head('反結帳')+'<button class="choice danger" data-action="cancel-order"><strong>整單取消</strong><span>保留在歷史訂單，不打印</span></button><button class="choice" data-action="reuse-order"><strong>反結帳並重用</strong><span>原有商品載入點單頁，可刪除、修改及新增</span></button><footer><button data-action="close-modal">返回</button></footer>');
  if(modal==='payment')return overlay(head('更改渠道／付款方式')+'<label>渠道</label><div class="option-grid">'+sources.map(x=>'<button data-choice="source" data-value="'+x+'" class="'+(x===o.source?'active':'')+'">'+x+'</button>').join('')+'</div><label>付款方式</label><div class="option-grid">'+payments.map(x=>'<button data-choice="payment" data-value="'+x+'" class="'+(x===o.paymentMethod?'active':'')+'">'+x+'</button>').join('')+'</div><footer><button data-action="close-modal">返回</button><button class="primary" data-action="save-payment">儲存更改</button></footer>');
  if(modal==='reprint')return overlay(head('選擇重印文件')+'<div class="check-list">'+['製作單','打包單','飯糰標籤','其他標籤','收據'].map(x=>'<label><input type="checkbox" name="document" value="'+x+'">'+x+'</label>').join('')+'</div><footer><button data-action="close-modal">返回</button><button class="primary" data-action="confirm-reprint">加入打印隊列</button></footer>');
  if(modal==='partial')return overlay(head('部分取消')+'<p>選擇商品及取消數量；已取消數量會保留在訂單紀錄。</p><div class="cancel-list">'+(o.items||[]).map((x,i)=>'<label><span>'+escapeHtml(x.name)+'｜現有 '+x.qty+'</span><select data-cancel-index="'+i+'"><option value="0">不取消</option>'+Array.from({length:x.qty},(_,n)=>'<option value="'+(n+1)+'">取消 '+(n+1)+'</option>').join('')+'</select></label>').join('')+'</div><footer><button data-action="close-modal">返回</button><button class="danger" data-action="confirm-partial">確認部分取消</button></footer>');
  if(modal==='timeline')return overlay(head('操作紀錄')+'<div class="timeline">'+((o.audit||[]).length?(o.audit||[]).slice().reverse().map(x=>'<p><b>'+escapeHtml(x.type)+'</b><span>'+escapeHtml(x.terminalId||'系統')+' · '+new Date(x.at).toLocaleString('zh-HK')+'</span></p>').join(''):'<p>暫時未有操作紀錄</p>')+'</div><footer><button data-action="close-modal">返回</button></footer>');return '';
}
function render(){const shown=visible();if(!shown.some(o=>o.id===selectedId))selectedId=shown[0]?.id||'';const p=orders.filter(o=>!isHistory(o)&&String(o.paymentStatus).includes('待')).length,b=orders.filter(o=>!isHistory(o)&&o.printStatus==='異常').length,h=orders.filter(isHistory).length;app.innerHTML='<main><header class="topbar"><div class="brand">磨飯 SMT</div><span class="terminal">'+terminalId+'</span><span class="online">● 接單中</span><div class="spacer"></div><button data-action="show-active">進行中 '+orders.filter(o=>!isHistory(o)).length+'</button><button data-action="show-history">歷史訂單 '+h+'</button></header><section class="workspace"><header class="page-head"><div><h1>訂單</h1><p>所有操作會即時顯示結果並保存紀錄。</p></div><button data-action="cycle-source">來源：'+({all:'全部',onsite:'現場',owned:'自有渠道',platform:'外賣平台'}[filters.source])+'</button><button data-action="filter-payment" class="'+(filters.exception==='payment'?'active':'')+'">付款待核實 '+p+'</button><button data-action="filter-print" class="'+(filters.exception==='print'?'active':'')+'">打印異常 '+b+'</button><button data-action="clear-filter">清除篩選</button></header><section class="stats"><button data-action="show-active">進行中訂單<b>'+orders.filter(o=>!isHistory(o)).length+'</b></button><button data-action="filter-payment">付款待核實<b>'+p+'</b></button><button data-action="filter-print">打印異常<b>'+b+'</b></button><button data-action="show-history">歷史訂單<b>'+h+'</b></button></section><section class="orders-layout">'+detail()+'<div class="lanes">'+groups.map(g=>lane(...g)).join('')+'</div></section></section><nav class="bottom-nav"><button data-action="navigate-order">點餐</button><button class="active">訂單</button><button>堂食</button><button>售罄</button><button>更多</button></nav></main>'+modalHtml()+'<div id="toast" class="toast '+(notice?'show':'')+'">'+escapeHtml(notice)+'</div>';if(notice)setTimeout(()=>{notice='';render();},1800);}
function handle(b){const a=b.dataset.action,o=orders.find(x=>x.id===selectedId);
  if(a==='select-order'){selectedId=b.dataset.id;render();}else if(a==='navigate-order')parent.postMessage({type:'morefun:navigate',route:'order'},'*');else if(a==='show-active'){filters.view='active';filters.exception='';render();}else if(a==='show-history'){filters.view='history';filters.exception='';render();}else if(a==='cycle-source'){filters.source={all:'onsite',onsite:'owned',owned:'platform',platform:'all'}[filters.source];render();}else if(a==='filter-payment'){filters.view='active';filters.exception=filters.exception==='payment'?'':'payment';render();}else if(a==='filter-print'){filters.view='active';filters.exception=filters.exception==='print'?'':'print';render();}else if(a==='clear-filter'){filters={view:'active',source:'all',exception:''};render();}else if(a==='reverse-open')open('reverse');else if(a==='change-payment')open('payment');else if(a==='reprint')open('reprint');else if(a==='partial-cancel')open('partial');else if(a==='timeline')open('timeline');else if(a==='close-modal'){modal='';render();}else if(a==='cancel-order')persist(cancelOrder(o,terminalId),'已取消 '+o.id+'，可在歷史訂單查看');else if(a==='save-payment'){const source=app.querySelector('[data-choice="source"].active')?.dataset.value||o.source,paymentMethod=app.querySelector('[data-choice="payment"].active')?.dataset.value||o.paymentMethod;persist(changeOrderPayment(o,{source,paymentMethod},terminalId),o.id+' 渠道及付款方式已更新');}else if(a==='confirm-reprint'){const docs=[...app.querySelectorAll('input[name="document"]:checked')].map(x=>x.value);if(!docs.length)return show('請先選擇打印文件');persist(queueReprint(o,docs,terminalId),o.id+' 已加入打印隊列：'+docs.join('、'));}else if(a==='confirm-partial'){let updated=o,count=0;[...app.querySelectorAll('[data-cancel-index]')].forEach(s=>{const qty=Number(s.value);if(qty){updated=partiallyCancelItem(updated,Number(s.dataset.cancelIndex),qty,terminalId);count+=qty;}});if(!count)return show('請先選擇取消數量');persist(updated,o.id+' 已部分取消 '+count+' 件；不會自動打印');}else if(a==='reuse-order'){writeJSON(ORDER_STORAGE_KEY,{cart:(o.items||[]).filter(x=>x.qty>0).map((x,i)=>({lineId:'reuse-'+o.id+'-'+i,productId:x.productId||'',name:x.name,image:x.image||'',qty:x.qty||1,unitPrice:Number(x.total||0)/Math.max(1,x.qty||1),total:Number(x.total||0),options:x.options||{},required:[],drinkSlots:0,drinkAssignments:[],createdOrder:i})),reuse:{orderId:o.id,startedByTerminalId:terminalId,startedAt:Date.now()},category:'全部'});persist(cancelOrder({...o,status:'reopened'},terminalId),o.id+' 已反結帳並載入點單頁');parent.postMessage({type:'morefun:navigate',route:'order'},'*');}}
function open(name){modal=name;render();}function show(text){notice=text;render();}
app.addEventListener('click',e=>{const choice=e.target.closest('[data-choice]');if(choice){app.querySelectorAll('[data-choice="'+choice.dataset.choice+'"]').forEach(x=>x.classList.remove('active'));choice.classList.add('active');return;}const b=e.target.closest('[data-action]');if(b)handle(b);});render();
