import {loadMenuCatalog} from '../pages/order/menu-api.js';
import {categories as fallbackCategories,products as fallbackProducts,drinks as fallbackDrinks} from '../pages/order/page-data.js';
import {ORDER_STORAGE_KEY,SUPPLY_STORAGE_KEY,readJSON,writeJSON,stableId} from '../shared/store.js';
import {cartPricingSummary,SERVICE_TAKEAWAY} from '../pages/order/order-domain.js';

const root=document.getElementById('smm-app');
const fallback={categories:fallbackCategories,products:fallbackProducts,drinks:fallbackDrinks};
const state={view:'dashboard',category:'全部',query:'',selected:null,qty:1,catalog:fallback,cart:[],supply:readJSON(SUPPLY_STORAGE_KEY,{})||{},ready:false};

function money(value){return `$${Number(value||0).toFixed(0)}`}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function productStatus(product){return state.supply?.[product.id]?.status||(product.available===false?'soldout':'available')}
function isBlocked(product){return ['soldout','paused'].includes(productStatus(product))}
function cartQty(){return state.cart.reduce((sum,row)=>sum+Number(row.qty||0),0)}
function saveCart(){const existing=readJSON(ORDER_STORAGE_KEY,{})||{};writeJSON(ORDER_STORAGE_KEY,{...existing,cart:state.cart,serviceMode:existing.serviceMode||SERVICE_TAKEAWAY,updatedAt:Date.now()})}
function loadCart(){const existing=readJSON(ORDER_STORAGE_KEY,{})||{};state.cart=Array.isArray(existing.cart)?existing.cart:[]}
function setView(view){state.view=view;state.selected=null;state.qty=1;render();window.scrollTo(0,0)}
function nav(){const rows=[['dashboard','⌂','工作台'],['menu','▣','點單'],['orders','▤','訂單'],['dine','⌂','堂食'],['more','•••','更多']];return `<nav class="smm-bottomnav">${rows.map(([id,icon,label])=>`<button type="button" data-view="${id}" class="${state.view===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')}</nav>`}
function topbar(title='磨飯 SMM'){return `<header class="smm-topbar"><div class="smm-brand"><span class="smm-brand-mark">磨</span><div><strong>${escapeHtml(title)}</strong><small>SMM Mobile Profile</small></div></div><button type="button" id="shell-online" class="smm-sync warn" data-sync-action><i></i>同步中</button></header>`}
function summary(){const sold=state.catalog.products.filter(product=>productStatus(product)==='soldout').length;return `<section class="smm-summary"><article><span>購物車</span><b>${cartQty()}</b></article><article><span>今日售罄</span><b>${sold}</b></article><article><span>待處理</span><b>0</b></article><article><span>打印工作</span><b>0</b></article></section>`}
function dashboard(){return `${topbar()}<main class="smm-main"><div class="smm-title"><h1>工作台</h1></div>${summary()}<section class="smm-quick"><button type="button" data-view="menu"><span>▣</span>現場點單</button><button type="button" data-view="orders"><span>▤</span>處理訂單</button><button type="button" data-view="soldout"><span>⊘</span>售罄管理</button><button type="button" data-view="dine"><span>⌂</span>堂食開枱</button></section></main>${nav()}`}
function categories(){return `<div class="smm-categories">${(state.catalog.categories||['全部']).map(name=>`<button type="button" data-category="${escapeHtml(name)}" class="${state.category===name?'active':''}">${escapeHtml(name)}</button>`).join('')}</div>`}
function productCard(product){const blocked=isBlocked(product);const image=product.image?`<img src="${escapeHtml(product.image)}" alt="">`:'<div class="smm-image">餐點圖片</div>';return `<article class="smm-product ${blocked?'sold':''}" data-product="${escapeHtml(product.id)}">${image}<div><h3>${escapeHtml(product.name)}</h3><p>${escapeHtml(product.description||product.category||'')}</p><strong>${money(product.price)}</strong></div>${blocked?`<span class="smm-soldtag">${productStatus(product)==='paused'?'暫停':'售罄'}</span>`:`<button type="button" class="smm-add" data-add-product="${escapeHtml(product.id)}">＋</button>`}</article>`}
function filteredProducts(){const query=state.query.trim().toLowerCase();return (state.catalog.products||[]).filter(product=>(state.category==='全部'||(product.categories||[product.category]).includes(state.category))&&(!query||`${product.name} ${product.code||''}`.toLowerCase().includes(query)))}
function menu(){const products=filteredProducts();return `${topbar('點單')}<main class="smm-main"><input class="smm-search" data-search value="${escapeHtml(state.query)}" placeholder="搜尋商品名稱或編號">${categories()}<section class="smm-products">${products.map(productCard).join('')||'<div class="smm-empty">未有符合商品</div>'}</section></main>${state.cart.length?cartBar():''}${nav()}`}
function detail(){const product=state.selected;if(!product)return menu();const blocked=isBlocked(product);return `${topbar('商品詳情')}<main class="smm-main smm-detail"><button type="button" class="smm-secondary" data-view="menu">返回點單</button><div class="smm-detail-hero">${product.image?`<img src="${escapeHtml(product.image)}" alt="">`:'餐點圖片'}</div><div><h2>${escapeHtml(product.name)}</h2><p>${escapeHtml(product.description||'')}</p><strong>${money(product.price)}</strong></div><article class="smm-card"><div class="smm-qty"><span>數量</span><div><button type="button" data-qty="-1">−</button><b>${state.qty}</b><button type="button" data-qty="1">＋</button></div></div></article>${product.required?.length?`<article class="smm-card"><b>需要選餐</b><p>此餐點包含 ${escapeHtml(product.required.join('、'))}。Mobile 選餐元件會直接共用 SMT Order Domain，未完成前不會繞過必選規則。</p></article>`:''}<button type="button" class="smm-primary" data-confirm-add ${blocked||product.required?.length?'disabled':''}>${blocked?'目前不可供應':product.required?.length?'需要完成選餐元件':`加入購物車 · ${money(product.price*state.qty)}`}</button></main>${nav()}`}
function createLine(product,qty){return {lineId:stableId('line'),lineType:'product',productId:product.id,name:product.name,image:product.image||'',category:product.category,categories:[...(product.categories||[product.category]).filter(Boolean)],qty,unitPrice:Number(product.price||0),total:Number(product.price||0)*qty,options:{},required:[...(product.required||[])],drinkSlots:Number(product.drinkSlots||0)*qty,drinkAssignments:[],combinable:Boolean(product.combinable),linkRole:product.linkRole||'',serviceMode:SERVICE_TAKEAWAY,serviceModeOverride:'',createdOrder:Date.now()+Math.random()}}
function addSelected(){const product=state.selected;if(!product||isBlocked(product)||product.required?.length)return;state.cart.push(createLine(product,state.qty));saveCart();setView('menu')}
function cartBar(){const summary=cartPricingSummary(state.cart);return `<button type="button" class="smm-cartbar" data-view="cart"><span>購物車 · ${cartQty()} 件</span><strong>${money(summary.total)}</strong></button>`}
function cart(){const summary=cartPricingSummary(state.cart);return `${topbar('購物車')}<main class="smm-main"><div class="smm-title"><h1>購物車</h1><button type="button" class="smm-secondary" style="width:auto;padding:0 14px" data-view="menu">繼續選購</button></div><section class="smm-list">${state.cart.map((line,index)=>`<article class="smm-row"><div><b>${escapeHtml(line.name)}</b><small>${line.qty} 件 · ${money(line.total)}</small></div><button type="button" class="smm-toggle sold" data-remove-line="${index}">移除</button></article>`).join('')||'<div class="smm-empty">購物車未有餐點</div>'}</section>${state.cart.length?`<article class="smm-card" style="margin-top:12px"><div class="smm-row"><span>餐點小計</span><b>${money(summary.foodSubtotal)}</b></div><div class="smm-row"><span>包裝費</span><b>${money(summary.packagingFee)}</b></div><div class="smm-row"><strong>總計</strong><strong>${money(summary.total)}</strong></div></article><button type="button" class="smm-primary" style="margin-top:12px" disabled>Order Commit 會於 P1 接入</button>`:''}</main>${nav()}`}
function soldout(){const rows=state.catalog.products||[];return `${topbar('售罄管理')}<main class="smm-main"><div class="smm-title"><h1>售罄管理</h1></div><section class="smm-list">${rows.map(product=>{const status=productStatus(product);return `<article class="smm-row"><div><b>${escapeHtml(product.name)}</b><small>${escapeHtml(product.code||product.id)}</small></div><button type="button" class="smm-toggle ${status==='available'?'available':'sold'}" data-toggle-supply="${escapeHtml(product.id)}">${status==='available'?'供應中':status==='paused'?'暫停':'售罄'}</button></article>`}).join('')}</section></main>${nav()}`}
function simplePage(title,text){return `${topbar(title)}<main class="smm-main"><div class="smm-title"><h1>${escapeHtml(title)}</h1></div><article class="smm-card"><p>${escapeHtml(text)}</p></article></main>${nav()}`}
function more(){return `${topbar('更多')}<main class="smm-main"><div class="smm-title"><h1>更多</h1></div><section class="smm-list"><button type="button" class="smm-row" data-view="soldout"><span><b>售罄管理</b><small>與 SMT 共用 Supply Runtime</small></span><span>›</span></button><button type="button" class="smm-row"><span><b>打印工作</b><small>SMM 只建立 Print Job，由 SMT／Android Host 執行</small></span><span>›</span></button><button type="button" class="smm-row"><span><b>同步狀態</b><small>Staff Session／離線 Queue／Runtime</small></span><span>›</span></button><button type="button" class="smm-row" data-logout><span><b>登出 Staff</b><small>保留購物車、餐牌及待同步 Queue</small></span><span>›</span></button></section></main>${nav()}`}
function render(){if(!root)return;const pages={dashboard,menu,detail,cart,soldout,orders:()=>simplePage('訂單','共用 SMT Order Authority；P1 Order Commit 完成後顯示正式 Incoming Queue。'),dine:()=>simplePage('堂食','堂食狀態將直接共用 SMT Dine Domain。'),more};root.innerHTML=(pages[state.view]||dashboard)()}
function updateSupply(productId){const current=readJSON(SUPPLY_STORAGE_KEY,{})||{};const status=current[productId]?.status||'available';const next={...current};if(status==='available')next[productId]={status:'soldout',updatedAt:Date.now(),source:'smm',deviceId:'SMM-01',canonicalProductId:productId};else delete next[productId];writeJSON(SUPPLY_STORAGE_KEY,next);state.supply=readJSON(SUPPLY_STORAGE_KEY,{})||{};window.MoreFunStartup?.supplyRuntime?.captureLocalSnapshot?.(next);render()}
function logout(){if(!confirm('確認登出 Staff？本機購物車、餐牌及待同步資料會保留。'))return;window.MoreFunStartup?.supplyRuntime?.logout?.();window.MoreFunStartup?.clearShellSession?.();document.documentElement.dataset.shellUnlocked='0';window.MoreFunStartup?.showLogin?.('已登出，請重新登入。')}
function bind(){root?.addEventListener('click',event=>{const logoutButton=event.target.closest('[data-logout]');if(logoutButton){logout();return}const view=event.target.closest('[data-view]')?.dataset.view;if(view){setView(view);return}const category=event.target.closest('[data-category]')?.dataset.category;if(category){state.category=category;render();return}const productId=event.target.closest('[data-add-product],[data-product]')?.dataset.addProduct||event.target.closest('[data-product]')?.dataset.product;if(productId){const product=state.catalog.products.find(row=>String(row.id)===String(productId));if(product&&!isBlocked(product)){state.selected=product;state.view='detail';state.qty=1;render()}return}const qty=event.target.closest('[data-qty]')?.dataset.qty;if(qty){state.qty=Math.max(1,state.qty+Number(qty));render();return}if(event.target.closest('[data-confirm-add]')){addSelected();return}const remove=event.target.closest('[data-remove-line]')?.dataset.removeLine;if(remove!==undefined){state.cart.splice(Number(remove),1);saveCart();render();return}const supply=event.target.closest('[data-toggle-supply]')?.dataset.toggleSupply;if(supply){updateSupply(supply)}});root?.addEventListener('input',event=>{if(event.target.matches('[data-search]')){state.query=event.target.value;render()}})}
async function boot(){loadCart();try{state.catalog=await loadMenuCatalog({fallback})}catch{state.catalog=fallback}state.supply=readJSON(SUPPLY_STORAGE_KEY,{})||{};state.ready=true;render()}
window.addEventListener('morefun:shell-unlocked',()=>void boot());window.addEventListener('morefun:domain-state-changed',event=>{if(event.detail?.domain!=='supply')return;state.supply=event.detail.value||{};render()});window.addEventListener('morefun:supply-runtime-updated',event=>{state.supply=event.detail?.overrides||readJSON(SUPPLY_STORAGE_KEY,{})||{};render()});
bind();if(document.documentElement.dataset.shellUnlocked==='1')void boot();
