import {readJSON,writeJSON,SETTINGS_STORAGE_KEY} from '../../shared/store.js';
import {money,imageBlock,bindImageFallbacks,escapeHtml,showToast} from '../../shared/components.js';
import {categories as fallbackCategories,products as fallbackProducts} from '../order/page-data.js';
import {loadMenuCatalog} from '../order/menu-api.js';

const app=document.getElementById('app'),SUPPLY_KEY='morefun:smt:v1:supply-overrides',PANEL_KEY='morefun:smt:v1:soldout-panel';
const fallbackCatalog={categories:fallbackCategories,products:fallbackProducts};
let categories=fallbackCategories.filter(x=>!['搜尋','全部'].includes(x)),products=[...fallbackProducts],category='全部',filter='全部',query='',batch=false,selected=new Set(),detailId='',collapsed=new Set();
let settings=readJSON(SETTINGS_STORAGE_KEY,{}),panel={images:true,open:true,cardMode:'large',...readJSON(PANEL_KEY,{})},supply=readJSON(SUPPLY_KEY,{})||{};

const lastReset=new Date();lastReset.setHours(5,0,0,0);if(Date.now()<lastReset.getTime())lastReset.setDate(lastReset.getDate()-1);Object.keys(supply).forEach(id=>{if(supply[id]?.status==='soldout'&&Number(supply[id].updatedAt||0)<lastReset.getTime())delete supply[id];});writeJSON(SUPPLY_KEY,supply);
const statusOf=id=>supply[id]?.status||'available';
const statusLabel=s=>s==='soldout'?'今日售罄':s==='paused'?'暫停供應':'供應中';
const template=()=>['large','small','text'].includes(panel.cardMode)?panel.cardMode:'large';
const isPurpleRice=p=>['紫米','飯團'].some(word=>[p.category,p.name,p.code].join(' ').includes(word));

function visibleProducts(){
  return products.filter(p=>p.isVisible!==false)
    .filter(p=>category==='全部'||(category==='售罄'?statusOf(p.id)==='soldout':statusOf(p.id)!=='soldout'&&p.category===category))
    .filter(p=>filter==='全部'||filter==='售罄'&&statusOf(p.id)==='soldout'||filter==='停售'&&statusOf(p.id)==='paused'||filter==='供應中'&&statusOf(p.id)==='available')
    .filter(p=>!query||[p.code,p.name,p.category].join(' ').toLowerCase().includes(query.toLowerCase()))
    .map((p,index)=>({p,index})).sort((a,b)=>Number(statusOf(a.p.id)==='paused')-Number(statusOf(b.p.id)==='paused')||a.index-b.index).map(row=>row.p);
}
function productCard(p){
  const style=template(),status=statusOf(p.id),checked=selected.has(p.id),action=batch?'toggle-select':'open-product',code=settings.catalog?.showCode===false?'':'<small class="product-code">'+escapeHtml(p.code||'')+'</small>',state=status==='available'?'':'<em class="supply-state '+status+'">'+statusLabel(status)+'</em>',mark=batch?'<span class="selection-mark">'+(checked?'✓':'＋')+'</span>':'';
  const statusClass=status==='soldout'?'soldout':status==='paused'?'paused':'';
  const classes='product-card '+style+' supply-product '+(checked?'selected ':'')+statusClass;
  if(style==='text')return '<article class="'+classes+'"><button class="card-open" data-action="'+action+'" data-id="'+p.id+'"><span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+state+'</span><b class="product-price">'+money(p.price)+'</b>'+mark+'</button></article>';
  if(style==='small')return '<article class="'+classes+'"><button class="card-open" data-action="'+action+'" data-id="'+p.id+'">'+imageBlock(p.image,p.name,'product-thumb')+'<span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+state+'</span><b class="product-price">'+money(p.price)+'</b>'+mark+'</button></article>';
  return '<article class="'+classes+'"><button class="card-open" data-action="'+action+'" data-id="'+p.id+'">'+imageBlock(p.image,p.name,'product-hero')+'<div class="product-info"><span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+(settings.catalog?.showDescription!==false&&p.description?'<p class="product-description">'+escapeHtml(p.description)+'</p>':'')+state+'</span><b class="product-price">'+money(p.price)+'</b></div>'+mark+'</button></article>';
}
function groupedRows(items){const groups=new Map();items.forEach(p=>{if(!groups.has(p.category))groups.set(p.category,[]);groups.get(p.category).push(p);});return [...groups].map(([cat,rows])=>'<section class="supply-list-group '+(collapsed.has(cat)?'collapsed':'')+'"><button class="group-head" data-action="toggle-section" data-value="'+cat+'"><strong>'+cat+'</strong><span>'+rows.length+' 項</span><b>'+(collapsed.has(cat)?'＋':'−')+'</b></button><div class="group-lines">'+rows.map((p,i)=>'<button class="supply-row '+(panel.images?'':'no-image')+'" data-action="open-product" data-id="'+p.id+'"><span class="seq">'+(i+1)+'</span>'+(panel.images?imageBlock(p.image,p.name,'supply-row-img'):'')+'<span><strong>'+escapeHtml([p.code,p.name].filter(Boolean).join(' '))+'</strong><small>'+statusLabel(statusOf(p.id))+'</small></span></button>').join('')+'</div></section>').join('');}
function statusPanel(){const affected=products.filter(p=>statusOf(p.id)!=='available');return '<aside class="supply-panel '+(panel.open?'':'is-collapsed')+'"><header><div><small>按分類整理</small><h2>售罄列表（'+affected.length+'）</h2></div><button data-action="toggle-panel">'+(panel.open?'收起':'展開')+'</button></header>'+(panel.open?'<div class="panel-tools"><button data-action="toggle-list-images">'+(panel.images?'隱藏小圖':'顯示小圖')+'</button><small>今日售罄於翌日早上五時恢復</small></div><div class="supply-list">'+(affected.length?groupedRows(affected):'<div class="empty-state"><strong>目前全部供應中</strong><p>可點擊單一產品或使用批量選擇。</p></div>')+'</div><footer><button class="primary" data-action="start-batch">批量選擇</button></footer>':'')+'</aside>';}
function batchPanel(){const rows=products.filter(p=>selected.has(p.id));return '<aside class="supply-panel batch-panel"><header><div><small>批量處理</small><h2>待確認（'+rows.length+'）</h2></div></header><div class="supply-list">'+(rows.length?groupedRows(rows):'<div class="empty-state"><strong>未有選擇產品</strong><p>點擊產品卡任何位置加入。</p></div>')+'</div><footer class="batch-actions"><button data-action="apply-bulk" data-value="soldout" '+(rows.length?'':'disabled')+'>今日售罄</button><button data-action="apply-bulk" data-value="paused" '+(rows.length?'':'disabled')+'>暫停供應</button><button data-action="apply-bulk" data-value="available" '+(rows.length?'':'disabled')+'>恢復供應</button><button data-action="cancel-batch">返回</button></footer></aside>';}
function detail(){const p=products.find(x=>x.id===detailId);if(!p)return '';const status=statusOf(p.id);return '<button class="detail-scrim" data-action="close-detail"></button><aside class="readonly-detail supply-detail"><header><div><small>供應狀態設定</small><h2>'+escapeHtml([p.code,p.name].filter(Boolean).join(' '))+'</h2></div><button data-action="close-detail">×</button></header><div class="detail-body">'+imageBlock(p.image,p.name,'detail-image')+'<dl><div><dt>分類</dt><dd>'+p.category+'</dd></div><div><dt>價格</dt><dd>'+money(p.price)+'</dd></div><div><dt>目前狀態</dt><dd><em class="supply-state '+status+'">'+statusLabel(status)+'</em></dd></div><div><dt>產品說明</dt><dd>'+escapeHtml(p.description||'沒有額外說明')+'</dd></div></dl><p>只會更改供應狀態；產品內容、價格及選項不能在此修改。</p></div><footer class="detail-actions"><button data-action="set-single-status" data-value="soldout">今日售罄</button><button data-action="set-single-status" data-value="paused">暫停供應</button><button data-action="set-single-status" data-value="available">恢復供應</button><button data-action="close-detail">返回</button></footer></aside>';}
function render(){
  const list=visibleProducts(),style=template(),width=Number(settings.cart?.widthPercent||32),categorySelected=list.filter(p=>selected.has(p.id)).length;
  app.innerHTML='<main><header class="topbar"><div class="brand">磨飯 SMT</div><div class="page-title"><strong>售罄管理</strong><small>只改供應狀態，不改產品內容</small></div><div class="spacer"></div><label class="search-box"><span>⌕</span><input id="search" value="'+escapeHtml(query)+'" placeholder="搜尋產品名稱或編號"></label><div class="segmented status-filter">'+['全部','供應中','售罄','停售'].map(x=>'<button data-action="filter" data-value="'+x+'" class="'+(filter===x?'active':'')+'">'+x+'</button>').join('')+'</div></header><section class="workspace"><section class="soldout-grid" style="--side-width:'+width+'%"><section class="catalog soldout-catalog"><div class="purple-actions"><button data-action="purple-status" data-value="soldout">紫米售罄</button><button data-action="purple-status" data-value="available">紫米恢復</button><span>快速處理所有紫米及飯團產品</span></div><nav class="categories"><button data-action="category" data-value="全部" class="'+(category==='全部'?'active':'')+'">全部</button><button data-action="category" data-value="售罄" class="soldout-category '+(category==='售罄'?'active':'')+'">售罄 '+products.filter(p=>statusOf(p.id)==='soldout').length+'</button>'+categories.map(cat=>'<button data-action="category" data-value="'+cat+'" class="'+(category===cat?'active':'')+'">'+cat+'</button>').join('')+'</nav><div class="catalog-caption"><span>'+list.length+' 款產品</span><div class="card-mode segmented">'+[['large','大圖'],['small','小圖'],['text','純文字']].map(([value,label])=>'<button data-action="card-mode" data-value="'+value+'" class="'+(style===value?'active':'')+'">'+label+'</button>').join('')+'</div>'+(batch?'<div class="selection-tools"><b>此分類已選 '+categorySelected+'／'+list.length+'</b><button data-action="select-category-all">全選</button><button data-action="select-category-none">全不選</button></div>':'<button class="batch-entry" data-action="start-batch">一次性多選</button>')+'</div><div class="products products-'+style+'">'+list.map(productCard).join('')+'</div></section>'+(batch?batchPanel():statusPanel())+'</section></section><nav class="bottom-nav"><button data-action="navigate-order">點餐</button><button data-action="navigate-orders">訂單</button><button data-action="navigate-dine">堂食</button><button class="active">售罄</button><button>更多</button></nav></main>'+detail()+'<div id="toast" class="toast"></div>';bindImageFallbacks(app);
}
function setStatus(ids,status){ids.forEach(id=>{status==='available'?delete supply[id]:supply[id]={status,updatedAt:Date.now()};});writeJSON(SUPPLY_KEY,supply);}
function handle(b){const a=b.dataset.action;if(a==='category'){category=b.dataset.value;render();}else if(a==='filter'){filter=b.dataset.value;render();}else if(a==='card-mode'){panel.cardMode=b.dataset.value;writeJSON(PANEL_KEY,panel);render();}else if(a==='start-batch'){batch=true;selected.clear();render();}else if(a==='cancel-batch'){batch=false;selected.clear();render();}else if(a==='toggle-select'){selected.has(b.dataset.id)?selected.delete(b.dataset.id):selected.add(b.dataset.id);render();}else if(a==='select-category-all'){visibleProducts().forEach(p=>selected.add(p.id));render();}else if(a==='select-category-none'){visibleProducts().forEach(p=>selected.delete(p.id));render();}else if(a==='apply-bulk'){setStatus(selected,b.dataset.value);const n=selected.size;batch=false;selected.clear();render();showToast('已處理 '+n+' 款產品');}else if(a==='purple-status'){const ids=products.filter(isPurpleRice).map(p=>p.id);setStatus(ids,b.dataset.value);render();showToast('已處理 '+ids.length+' 款紫米產品');}else if(a==='open-product'){detailId=b.dataset.id;render();}else if(a==='set-single-status'){setStatus([detailId],b.dataset.value);detailId='';render();showToast('供應狀態已更新');}else if(a==='close-detail'){detailId='';render();}else if(a==='toggle-section'){collapsed.has(b.dataset.value)?collapsed.delete(b.dataset.value):collapsed.add(b.dataset.value);render();}else if(a==='toggle-panel'){panel.open=!panel.open;writeJSON(PANEL_KEY,panel);render();}else if(a==='toggle-list-images'){panel.images=!panel.images;writeJSON(PANEL_KEY,panel);render();}else if(a.startsWith('navigate-'))window.parent?.postMessage?.({type:'morefun:navigate',route:a.replace('navigate-','')},'*');}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handle(b);});app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;render();}});render();loadMenuCatalog({fallback:fallbackCatalog}).then(r=>{categories=(r.categories||fallbackCategories).filter(x=>!['搜尋','全部'].includes(x));products=(r.products||fallbackProducts).filter(p=>p.isVisible!==false);render();}).catch(error=>{console.error('SOLDOUT_MENU_BOOTSTRAP_FAILED',error);categories=fallbackCategories.filter(x=>!['搜尋','全部'].includes(x));products=[...fallbackProducts];render();showToast('餐牌連接失敗，已載入本機售罄管理');});
