import {readJSON,writeJSON,SETTINGS_STORAGE_KEY} from '../../shared/store.js';
import {money,imageBlock,bindImageFallbacks,escapeHtml,showToast} from '../../shared/components.js';
import {categories as fallbackCategories,products as fallbackProducts,drinks as fallbackDrinks} from '../order/page-data.js';
import {loadMenuCatalog} from '../order/menu-api.js';
const app=document.getElementById('app'),SUPPLY_KEY='morefun:smt:v1:supply-overrides',PANEL_KEY='morefun:smt:v1:soldout-panel';
const fallbackCatalog={categories:fallbackCategories,products:fallbackProducts,drinks:fallbackDrinks};
let categories=fallbackCategories.filter(x=>!['搜尋','全部'].includes(x)),products=[...fallbackProducts],category='全部',filter='全部',query='',batch=false,selected=new Set(),detailId='',collapsed=new Set();
let settings=readJSON(SETTINGS_STORAGE_KEY,{}),panel={images:true,open:true,...readJSON(PANEL_KEY,{})},supply=readJSON(SUPPLY_KEY,{})||{};
const lastReset=new Date();lastReset.setHours(5,0,0,0);if(Date.now()<lastReset.getTime())lastReset.setDate(lastReset.getDate()-1);Object.keys(supply).forEach(id=>{if(supply[id]?.status==='soldout'&&Number(supply[id].updatedAt||0)<lastReset.getTime())delete supply[id];});writeJSON(SUPPLY_KEY,supply);
const statusOf=id=>supply[id]?.status||'available';
const statusLabel=s=>s==='soldout'?'今日售罄':s==='paused'?'暫停供應':'供應中';
const template=()=>settings.catalog?.defaultTemplate||'large';
function visibleProducts(){return products.filter(p=>p.isVisible!==false).filter(p=>category==='全部'||p.category===category).filter(p=>filter==='全部'||filter==='售罄'&&statusOf(p.id)==='soldout'||filter==='停售'&&statusOf(p.id)==='paused'||filter==='供應中'&&statusOf(p.id)==='available').filter(p=>!query||[p.code,p.name,p.category].join(' ').toLowerCase().includes(query.toLowerCase()));}
function productCard(p){
  const style=template(),status=statusOf(p.id),checked=selected.has(p.id),code=settings.catalog?.showCode===false?'':'<small class="product-code">'+escapeHtml(p.code||'')+'</small>',state=status==='available'?'':'<em class="supply-state '+status+'">'+statusLabel(status)+'</em>',toggle=batch?'<button class="select-switch '+(checked?'active':'')+'" data-action="toggle-select" data-id="'+p.id+'"><span></span></button>':'';
  if(style==='text')return '<article class="product-card text supply-product '+(checked?'selected':'')+'"><button class="card-open" data-action="open-product" data-id="'+p.id+'"><span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+state+'</span><b class="product-price">'+money(p.price)+'</b></button>'+toggle+'</article>';
  if(style==='small')return '<article class="product-card small supply-product '+(checked?'selected':'')+'"><button class="card-open" data-action="open-product" data-id="'+p.id+'">'+imageBlock(p.image,p.name,'product-thumb')+'<span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+state+'</span><b class="product-price">'+money(p.price)+'</b></button>'+toggle+'</article>';
  return '<article class="product-card large supply-product '+(checked?'selected':'')+'"><button class="card-open" data-action="open-product" data-id="'+p.id+'">'+imageBlock(p.image,p.name,'product-hero')+'<div class="product-info"><span class="product-copy">'+code+'<strong>'+escapeHtml(p.name)+'</strong>'+(settings.catalog?.showDescription!==false&&p.description?'<p class="product-description">'+escapeHtml(p.description)+'</p>':'')+state+'</span><b class="product-price">'+money(p.price)+'</b></div></button>'+toggle+'</article>';
}
function groupedRows(items){const groups=new Map();items.forEach(p=>{if(!groups.has(p.category))groups.set(p.category,[]);groups.get(p.category).push(p);});return [...groups].map(([cat,rows])=>'<section class="supply-list-group '+(collapsed.has(cat)?'collapsed':'')+'"><button class="group-head" data-action="toggle-section" data-value="'+cat+'"><strong>'+cat+'</strong><span>'+rows.length+' 項</span><b>'+(collapsed.has(cat)?'＋':'−')+'</b></button><div class="group-lines">'+rows.map((p,i)=>'<button class="supply-row '+(panel.images?'':'no-image')+'" data-action="open-product" data-id="'+p.id+'"><span class="seq">'+(i+1)+'</span>'+(panel.images?imageBlock(p.image,p.name,'supply-row-img'):'')+'<span><strong>'+escapeHtml([p.code,p.name].filter(Boolean).join(' '))+'</strong><small>'+statusLabel(statusOf(p.id))+'</small></span></button>').join('')+'</div></section>').join('');}
function statusPanel(){const affected=products.filter(p=>statusOf(p.id)!=='available');return '<aside class="supply-panel '+(panel.open?'':'is-collapsed')+'"><header><div><small>按分類整理</small><h2>售罄列表（'+affected.length+'）</h2></div><button data-action="toggle-panel">'+(panel.open?'收起':'展開')+'</button></header>'+(panel.open?'<div class="panel-tools"><button data-action="toggle-list-images">'+(panel.images?'隱藏小圖':'顯示小圖')+'</button><small>今日售罄於翌日早上五時恢復</small></div><div class="supply-list">'+(affected.length?groupedRows(affected):'<div class="empty-state"><strong>目前全部供應中</strong><p>批量選擇產品後設定狀態。</p></div>')+'</div><footer><button class="primary" data-action="start-batch">批量選擇</button></footer>':'')+'</aside>';}
function batchPanel(){const rows=products.filter(p=>selected.has(p.id));return '<aside class="supply-panel batch-panel"><header><div><small>批量處理</small><h2>待確認（'+rows.length+'）</h2></div></header><div class="supply-list">'+(rows.length?groupedRows(rows):'<div class="empty-state"><strong>未有選擇產品</strong><p>用產品卡右上角開關加入。</p></div>')+'</div><footer class="batch-actions"><button data-action="apply-bulk" data-value="soldout" '+(rows.length?'':'disabled')+'>今日售罄</button><button data-action="apply-bulk" data-value="paused" '+(rows.length?'':'disabled')+'>暫停供應</button><button data-action="apply-bulk" data-value="available" '+(rows.length?'':'disabled')+'>恢復供應</button><button data-action="cancel-batch">返回</button></footer></aside>';}
function detail(){const p=products.find(x=>x.id===detailId);if(!p)return '';return '<button class="detail-scrim" data-action="close-detail"></button><aside class="readonly-detail"><header><div><small>產品內容</small><h2>'+escapeHtml([p.code,p.name].filter(Boolean).join(' '))+'</h2></div><button data-action="close-detail">×</button></header><div class="detail-body">'+imageBlock(p.image,p.name,'detail-image')+'<dl><div><dt>分類</dt><dd>'+p.category+'</dd></div><div><dt>價格</dt><dd>'+money(p.price)+'</dd></div><div><dt>目前狀態</dt><dd>'+statusLabel(statusOf(p.id))+'</dd></div><div><dt>產品說明</dt><dd>'+escapeHtml(p.description||'沒有額外說明')+'</dd></div></dl><p>只供參考，不能修改；產品內容要到後台產品管理更改。</p></div><footer><button data-action="close-detail">返回</button></footer></aside>';}
function render(){const list=visibleProducts(),style=template(),width=Number(settings.cart?.widthPercent||32);app.innerHTML='<main><header class="topbar"><div class="brand">磨飯 SMT</div><div class="page-title"><strong>售罄管理</strong><small>只改供應狀態，不改產品內容</small></div><div class="spacer"></div><label class="search-box"><span>⌕</span><input id="search" value="'+escapeHtml(query)+'" placeholder="搜尋產品名稱或編號"></label><div class="segmented status-filter">'+['全部','供應中','售罄','停售'].map(x=>'<button data-action="filter" data-value="'+x+'" class="'+(filter===x?'active':'')+'">'+x+'</button>').join('')+'</div></header><section class="workspace"><section class="soldout-grid" style="--side-width:'+width+'%"><section class="catalog soldout-catalog"><nav class="categories"><button data-action="category" data-value="全部" class="'+(category==='全部'?'active':'')+'">全部</button>'+categories.map(cat=>'<button data-action="category" data-value="'+cat+'" class="'+(category===cat?'active':'')+'">'+cat+'</button>').join('')+'</nav><div class="catalog-caption"><span>產品卡與點單頁保持一致</span><strong>'+list.length+' 款產品</strong></div><div class="products products-'+style+'">'+list.map(productCard).join('')+'</div></section>'+(batch?batchPanel():statusPanel())+'</section></section><nav class="bottom-nav"><button data-action="navigate-order">點餐</button><button data-action="navigate-orders">訂單</button><button data-action="navigate-dine">堂食</button><button class="active">售罄</button><button>更多</button></nav></main>'+detail()+'<div id="toast" class="toast"></div>';bindImageFallbacks(app);}
function handle(b){const a=b.dataset.action;if(a==='category'){category=b.dataset.value;render();}else if(a==='filter'){filter=b.dataset.value;render();}else if(a==='start-batch'){batch=true;selected.clear();render();}else if(a==='cancel-batch'){batch=false;selected.clear();render();}else if(a==='toggle-select'){selected.has(b.dataset.id)?selected.delete(b.dataset.id):selected.add(b.dataset.id);render();}else if(a==='apply-bulk'){selected.forEach(id=>{b.dataset.value==='available'?delete supply[id]:supply[id]={status:b.dataset.value,updatedAt:Date.now()};});writeJSON(SUPPLY_KEY,supply);const n=selected.size;batch=false;selected.clear();render();showToast('已處理 '+n+' 款產品');}else if(a==='open-product'){detailId=b.dataset.id;render();}else if(a==='close-detail'){detailId='';render();}else if(a==='toggle-section'){collapsed.has(b.dataset.value)?collapsed.delete(b.dataset.value):collapsed.add(b.dataset.value);render();}else if(a==='toggle-panel'){panel.open=!panel.open;writeJSON(PANEL_KEY,panel);render();}else if(a==='toggle-list-images'){panel.images=!panel.images;writeJSON(PANEL_KEY,panel);render();}else if(a.startsWith('navigate-'))window.parent?.postMessage?.({type:'morefun:navigate',route:a.replace('navigate-','')},'*');}
app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handle(b);});app.addEventListener('input',e=>{if(e.target.id==='search'){query=e.target.value;render();}});render();loadMenuCatalog({fallback:fallbackCatalog}).then(r=>{categories=(r.categories||fallbackCategories).filter(x=>!['搜尋','全部'].includes(x));products=(r.products||fallbackProducts).filter(p=>p.isVisible!==false);render();}).catch(error=>{console.error('SOLDOUT_MENU_BOOTSTRAP_FAILED',error);categories=fallbackCategories.filter(x=>!['搜尋','全部'].includes(x));products=[...fallbackProducts];render();showToast('餐牌連接失敗，已載入本機售罄管理');});
