import {categories,products,initialCart,quickDrinks} from './page-data.js';
const app=document.getElementById('app');
const state={category:'全部',cart:[...initialCart],card:null,pending:false,search:false,selectedDrink:null,settings:false,quick:true,drinkMode:'all',showDrinks:true};
const money=value=>`$${Number(value).toFixed(0)}`;
function top(){return `<header class="topbar"><div class="brand"><span class="logo"></span><span>磨飯 SMT</span></div><div class="serial"><small>流水號</small><strong>10248</strong></div><div class="top-spacer"></div><button class="top-action" data-action="pending">待處理 <span class="badge">8</span></button><button class="top-action" data-action="quick-settings">快速 <span class="switch ${state.quick?'on':''}"></span></button><button class="top-action online">● 線上</button></header>`}
function nav(){return `<nav class="bottom-nav"><button class="active" data-route="order">點單</button><button data-route="orders">訂單</button><button data-route="dine">堂食</button><button data-route="supply">售罄</button><button data-route="more">更多</button></nav>`}
function cartRows(){return state.cart.map(row=>`<button class="cart-row" data-action="edit" data-id="${row.id}"><img src="${row.image}" alt=""><span><h3>${row.name}</h3><small>${row.detail}</small></span><span class="cart-price">x${row.qty}<br>${money(row.total)}</span></button>`).join('')}
function productRows(){return products.filter(p=>state.category==='全部'||state.category==='人氣推薦'&&p.tag||p.category===state.category).map(p=>`<button class="product" data-action="add" data-id="${p.id}">${p.tag?`<span class="tag">${p.tag}</span>`:''}<img src="${p.image}" alt=""><div class="meta"><h3>${p.name}</h3><small>${p.code}</small><strong>${money(p.price)}</strong></div></button>`).join('')}
function editCard(){const row=state.cart.find(x=>x.id===state.editId)||state.cart[0];return `<section class="workspace-card"><header><strong>修改卡｜${row.name}</strong><button class="close" data-action="close-card">×</button></header><div class="body"><div class="field"><h4>飯量</h4><div class="options"><button class="option active">標準</button><button class="option">少飯</button><button class="option">半飯</button><button class="option">多飯</button></div></div><div class="field"><h4>調整</h4><div class="options"><button class="option">走蛋</button><button class="option active">少醬</button><button class="option">走蔥</button></div></div><div class="field"><h4>備註（可選）</h4><textarea class="btn" style="width:100%;height:90px" placeholder="只顯示有填寫的備註"></textarea></div><button class="btn primary" style="width:100%" data-action="close-card">儲存修改</button></div></section>`}
function completionCard(){return `<section class="workspace-card"><header><strong>待補區 <span class="badge">2</span></strong><button class="close" data-action="close-card">×</button></header><div class="body"><section class="completion-section"><header><h3 style="color:var(--red)">必須項目</h3><b>不可結帳</b></header><p>紫米飯團 A 餐尚欠飲品 1 份。</p><button class="btn primary">立即補選</button></section><section class="completion-section"><header><h3 style="color:var(--green)">可組合</h3><b>可略過</b></header><p>購物車內可組成飯團套餐 ×2，沒有選擇仍可結帳。</p><button class="btn">選擇購物車內小食</button></section></div></section>`}
function pendingCard(){return `<section class="workspace-card"><header><strong>待處理</strong><button class="close" data-action="close-card">×</button></header><div class="body"><section class="pending-section"><strong>新 App／Web 單 <span class="badge">5</span></strong><div><span>A512 小米粒</span><b>3件</b></div><div><span>A513 陳小姐</span><b>2件</b></div></section><section class="pending-section"><strong>電話／WhatsApp 核對 <span class="badge">3</span></strong><div><span>TK0252 張先生</span><b>核對中</b></div></section></div></section>`}
function settings(){return `<div class="modal-backdrop"><section class="modal settings-modal"><header><h2>快速模式與快捷飲品設定</h2><button class="close" data-action="settings-close">×</button></header><section class="settings-section"><button class="settings-head">A　快速模式 <span>⌃</span></button><div class="settings-body"><div class="mode-grid"><button class="mode-card ${!state.quick?'active':''}" data-action="mode" data-value="normal"><h3>普通模式</h3><p>商品有必選時，先完成產品詳細頁，之後才加入購物車。</p></button><button class="mode-card ${state.quick?'active':''}" data-action="mode" data-value="quick"><h3>快速模式</h3><p>即時加入購物車，未完成項目自動放入待補區。</p></button></div></div></section><section class="settings-section"><button class="settings-head">B　快捷飲品 <span>⌃</span></button><div class="settings-body"><div class="mode-grid"><button class="mode-card ${state.drinkMode==='all'?'active':''}" data-action="drink-mode" data-value="all"><h3>全部套餐可選飲品</h3><p>以純文字一行顯示所有可選飲品。</p></button><button class="mode-card ${state.drinkMode==='custom'?'active':''}" data-action="drink-mode" data-value="custom"><h3>自訂飲品</h3><p>以小圖標＋文字顯示，順序由後台設定。</p></button></div><div class="settings-row"><span>顯示快捷飲品區域</span><button class="switch ${state.showDrinks?'on':''}" data-action="toggle-drinks"></button></div><div class="drink-preview">${quickDrinks.slice(0,6).map(x=>`<div class="drink-mini">${x}</div>`).join('')}</div></div></section><div class="settings-foot"><button class="btn" data-action="settings-reset">重設</button><button class="btn primary" data-action="settings-close">套用設定</button></div></section></div>`}
function render(){const card=state.card==='edit'?editCard():state.card==='completion'?completionCard():state.card==='pending'?pendingCard():'';app.innerHTML=`<div class="app">${top()}<main class="workspace"><section class="order-layout"><aside class="cart panel"><div class="cart-head"><h2>購物車（${state.cart.reduce((n,x)=>n+x.qty,0)}）</h2><button class="btn" data-action="clear">清空</button></div><div class="cart-list">${cartRows()}</div><div class="cart-foot"><button class="completion-bar" data-action="completion"><span>待補區</span><span><b class="badge">2</b>　⌄</span></button><div class="cart-actions"><button class="btn">暫存</button><button class="btn primary" data-action="checkout">結帳 $430</button></div></div></aside><section class="catalog panel ${state.card?'frosted':''}"><div class="catalog-top"><div class="category-grid">${categories.map(x=>`<button class="${state.category===x?'active':''}" data-action="category" data-value="${x}">${x}</button>`).join('')}</div></div><div class="product-area"><div class="products">${productRows()}</div></div>${state.showDrinks?`<div class="quick-drinks">${quickDrinks.map(x=>`<button class="${state.selectedDrink===x?'selected':''}" data-action="drink" data-value="${x}">${x}</button>`).join('')}</div>`:''}</section>${card}</section></main>${nav()}</div>${state.search?`<div class="search-pop"><button class="close" data-action="search-close">×</button><h3>搜尋商品</h3><input placeholder="輸入商品名稱或編號"></div>`:''}${state.settings?settings():''}`;bind()}
function bind(){document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{const a=button.dataset.action;if(a==='pending')state.card='pending';if(a==='quick-settings')state.settings=true;if(a==='edit'){state.card='edit';state.editId=button.dataset.id}if(a==='completion')state.card='completion';if(a==='close-card')state.card=null;if(a==='category'){if(button.dataset.value==='搜尋')state.search=true;else state.category=button.dataset.value}if(a==='search-close')state.search=false;if(a==='drink')state.selectedDrink=button.dataset.value;if(a==='mode')state.quick=button.dataset.value==='quick';if(a==='drink-mode')state.drinkMode=button.dataset.value;if(a==='toggle-drinks')state.showDrinks=!state.showDrinks;if(a==='settings-close')state.settings=false;if(a==='settings-reset'){state.quick=true;state.drinkMode='all';state.showDrinks=true}if(a==='clear')state.cart=[];if(a==='add'){const p=products.find(x=>x.id===button.dataset.id);showToast(`已加入 ${p.name}`)}if(a==='checkout')window.MoreFunPageBridge.navigate('checkout');render()}))}
function showToast(text){const toast=document.getElementById('toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1500)}
render();
