from pathlib import Path
import re

js=Path('smt-app.js')
css=Path('smt-app.css')
html=Path('index.html')
status=Path('FULL_PORT_STATUS.md')

s=js.read_text(encoding='utf-8')
s=s.replace("pendingGroupOpen:{'磨飯 App':true,'電話／WhatsApp':true},quick:true,quickMode:'all',","pendingGroupOpen:{'磨飯 App':true,'電話／WhatsApp':true},quickModeEnabled:true,")
s=s.replace("快捷 ${state.quick?'ON':'OFF'}","快捷 ${state.quickModeEnabled?'ON':'OFF'}")
s=s.replace("function quickStrip(){if(!state.quick||!state.settings.quickDrinks.enabled)return '';return","function quickStrip(){if(!state.settings.quickDrinks.enabled)return '';return")

start=s.index('function sideCard(){')
end=s.index('function pendingPanel(){')
side=r'''function sideCard(){
  if(state.card==='settings')return `<aside class="side-card"><header><strong>顯示設定</strong><button data-action="close-card">×</button></header><section><label>產品卡預設</label><div class="chips">${[['large','大圖'],['small','小圖'],['text','純文字']].map(([value,label])=>`<button data-action="set-template" data-value="${value}" class="${state.settings.catalog.defaultTemplate===value?'active':''}">${label}</button>`).join('')}</div></section><section><label><input type="checkbox" data-action="toggle-code" ${state.settings.catalog.showCode?'checked':''}> 顯示產品代碼</label></section><section><label><input type="checkbox" data-action="toggle-quick-strip" ${state.settings.quickDrinks.enabled?'checked':''}> 顯示快捷飲品列</label></section><section><label><input type="checkbox" data-action="toggle-images" ${state.settings.quickDrinks.showImages?'checked':''}> 快捷飲品顯示圖片</label></section><section><label>購物籃合拼</label><div class="chips">${[['same_config','相同設定'],['always','永遠'],['never','不合拼']].map(([value,label])=>`<button data-action="set-merge" data-value="${value}" class="${state.settings.cart.mergeMode===value?'active':''}">${label}</button>`).join('')}</div></section></aside>`;
  if(state.card==='health')return `<aside class="side-card"><header><strong>系統狀態</strong><button data-action="close-card">×</button></header>${Object.values(state.health).map(item=>`<section class="health-row ${item.ok?'ok':'bad'}"><b>${item.label}</b><span>${item.detail}</span></section>`).join('')}<button class="side-action" data-action="refresh-health">重新檢查</button></aside>`;
  if(state.card==='status')return `<aside class="side-card"><header><strong>接單狀態</strong><button data-action="close-card">×</button></header><section><div class="chips"><button data-action="set-operation" data-value="open" class="${state.operations.acceptingOrders&&!state.operations.immediateStopped?'active':''}">接單中</button><button data-action="set-operation" data-value="stop" class="${state.operations.immediateStopped?'active':''}">立即停單</button></div></section><section><label>預定停止時間</label><input class="time-input" type="time" data-action="set-close-time" value="${esc(state.operations.scheduledClose||'')}"></section></aside>`;
  if(state.card==='pending')return pendingPanel();
  if(state.card==='quick')return `<aside class="side-card quick-card"><header><strong>快捷模式</strong><button data-action="close-card">×</button></header><section><label><input type="checkbox" data-action="toggle-quick-mode" ${state.quickModeEnabled?'checked':''}> 啟用快捷下單</label><small>開啟後，點任何產品都會立即加入購物車，即使未完成必選；之後再由待補區整理。</small></section><section><label><input type="checkbox" data-action="toggle-quick-strip" ${state.settings.quickDrinks.enabled?'checked':''}> 顯示快捷飲品列</label></section><section><label><input type="checkbox" data-action="toggle-images" ${state.settings.quickDrinks.showImages?'checked':''}> 顯示飲品圖片</label></section></aside>`;
  if(state.card==='completion')return completionSideCard();
  if(state.card==='edit')return editSideCard();
  return '';
}
function cardLayer(){const card=sideCard();return card?`<div class="card-layer"><button class="card-scrim" data-action="close-card" aria-label="關閉卡片"></button>${card}</div>`:'';}
function completionSideCard(){const required=pendingSummary(),link=linkUpSummary();return `<aside class="side-card completion-side-card"><header><strong>整理待補區</strong><button data-action="close-card">×</button></header><section><h3>必須完成</h3>${required.total?Object.entries(required).filter(([key,value])=>key!=='total'&&value).map(([key,value])=>`<p class="summary-row"><span>${key==='rice'?'飯底':key==='sauce'?'醬汁':key==='snack'?'小食':'飲品'}</span><b>${value}</b></p>`).join(''):'<div class="complete-message">所有必選已完成</div>'}</section><section><h3>可選／可組合</h3><p class="summary-row"><span>單點飯團</span><b>${link.riceballs}</b></p><p class="summary-row"><span>獨立小食</span><b>${link.snacks}</b></p><p class="summary-row"><span>獨立飲品</span><b>${link.drinks}</b></p>${link.count?`<button class="primary full" data-action="apply-link-up" data-value="${link.count}">組合 ${link.count} 份套餐</button>`:'<small>未有足夠組合項目</small>'}</section></aside>`;}
function editSideCard(){const modal=state.modal;if(!modal||modal.type!=='product'||!modal.lineId)return '';const product=productMap.get(modal.productId),draft=modal.draft;const groups=[...new Set([...(draft.requiredGroups||[]),...(draft.optionalGroups||[])])].filter(group=>!['drink','sweetness','ice'].includes(group));return `<aside class="side-card edit-side-card"><header><div>${imageBlock(product.image,product.name,'edit-thumb')}<span><small>${product.code}</small><strong>${esc(product.name)}</strong></span></div><button data-action="close-card">×</button></header><div class="side-scroll">${groups.map(group=>`<section class="option-group"><header><strong>${group==='rice'?'飯底':group==='sauce'?'醬汁':group==='adjustment'?'飯量':'小食'}</strong><span>${draft.requiredGroups.includes(group)?'必選':'選填'}</span></header><div class="chips">${(DATA.optionSets[group]||[]).map(value=>`<button data-action="choose-option" data-group="${group}" data-value="${value}" class="${draft.options[group]===value?'active':''}">${value}</button>`).join('')}</div></section>`).join('')}${draft.requiredGroups.includes('drink')||draft.optionalGroups.includes('drink')?`<section class="option-group"><header><strong>飲品</strong><span>${draft.requiredGroups.includes('drink')?'必選':'選填'}</span></header><div class="drink-scroll">${DATA.drinks.map(drink=>drinkCard(drink,'choose-detail-drink')).join('')}</div></section>`:''}</div><footer class="side-footer"><div class="qty"><button data-action="qty-minus">−</button><button data-action="open-keypad">${draft.qty}</button><button data-action="qty-plus">＋</button></div><div class="edit-actions"><button class="danger ghost" data-action="delete-line">刪除</button><button class="primary" data-action="apply-product">確認修改</button></div></footer></aside>`;}
'''
s=s[:start]+side+s[end:]
s=s.replace('${sideCard()}</section></main>','${cardLayer()}</section></main>')
s=s.replace("state.modal={type:'product',productId,lineId,draft,applyQty:existing?existing.qty:1,dirty:false};drawProductModal();","state.modal={type:'product',productId,lineId,draft,applyQty:existing?existing.qty:1,dirty:false};if(lineId){state.card='edit';render();}else drawProductModal();")
s=s.replace("function drawProductModal(){const modal=state.modal;if(!modal||modal.type!=='product')return;","function drawProductModal(){const modal=state.modal;if(!modal||modal.type!=='product')return;if(modal.lineId){render();return;}")
s=s.replace("function openConfirm(title,text,onConfirm){state.modal={type:'confirm',dirty:false,onConfirm};","function openConfirm(title,text,onConfirm){const previousModal=state.modal;state.modal={type:'confirm',dirty:false,onConfirm,previousModal};")
s=s.replace("function openCompletion(){const required=pendingSummary(),link=linkUpSummary();mountModal(","function openCompletion(){state.modal=null;state.card='completion';render();return;mountModal(")
s=s.replace("state.modal=null;render();toast(modal.lineId?'修改已套用':'已加入購物車');","state.modal=null;state.card=null;render();toast(modal.lineId?'修改已套用':'已加入購物車');")
insert="function quickAddProduct(productId){const product=productMap.get(productId);if(!product)return;const draft=normalizeLine({productId,qty:1,options:{},drinkAssignments:[]});state.cart=mergeCart([...state.cart,draft]);render();toast('已快速加入，可稍後在待補區整理');}\n"
s=s.replace('function assignQuickDrink(drinkId)',insert+'function assignQuickDrink(drinkId)')
s=s.replace("else if(action==='open-product')openProduct(element.dataset.id);","else if(action==='open-product'){if(state.quickModeEnabled)quickAddProduct(element.dataset.id);else openProduct(element.dataset.id);}")
s=s.replace("else if(action==='close-card'){state.card=null;render();}","else if(action==='close-card'){if(state.card==='edit'&&state.modal?.dirty)return openConfirm('尚未套用修改','離開會失去今次修改。',()=>{state.card=null;state.modal=null;render();});state.card=null;if(state.modal?.lineId)state.modal=null;render();}")
s=s.replace("else if(action==='toggle-quick'){state.quick=!state.quick;render();}","else if(action==='toggle-quick-mode'){state.quickModeEnabled=!state.quickModeEnabled;render();}\n  else if(action==='toggle-quick-strip')updateSetting(settings=>settings.quickDrinks.enabled=!settings.quickDrinks.enabled);")
s=s.replace("else if(action==='cancel-confirm'){state.modal=null;render();}","else if(action==='cancel-confirm'){const previousModal=state.modal?.previousModal;state.modal=previousModal||null;render();}")
assert 'quickModeEnabled' in s and 'card-layer' in s and 'quickAddProduct' in s
js.write_text(s,encoding='utf-8')

c=css.read_text(encoding='utf-8')
start=c.index('.side-card,.pending-panel{')
end=c.index('.scrim{')
card_css=".card-layer{position:fixed;inset:0;z-index:40;pointer-events:auto}.card-scrim{position:absolute;inset:0;border:0;background:rgba(32,24,18,.34);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}.side-card,.pending-panel{position:absolute;right:20px;top:94px;bottom:86px;width:25%;height:auto;max-height:none;z-index:41;background:#fff;border:1px solid var(--line);border-radius:15px;box-shadow:var(--shadow);overflow:hidden;display:flex;flex-direction:column}.side-card>header,.pending-panel>header{display:flex;justify-content:space-between;align-items:center;padding:14px;border-bottom:1px solid var(--line);flex:none}.side-card>header>div{display:flex;align-items:center;gap:10px}.side-card header button,.pending-panel header button{width:40px;height:40px;border:0;border-radius:9px;background:#f4efea}.side-card>section{padding:14px;border-bottom:1px solid var(--line)}.side-card label{display:block;margin-bottom:9px;font-weight:850}.side-action,.expand-button{width:calc(100% - 28px);margin:14px;height:44px;border:1px solid var(--line);border-radius:9px;background:#fff;flex:none}.health-row{display:flex;justify-content:space-between}.health-row.ok{color:var(--green)}.health-row.bad{color:var(--danger)}.time-input{width:100%;height:48px;border:1px solid var(--line);border-radius:9px;padding:0 12px}.pending-scroll,.side-scroll{overflow:auto;min-height:0;flex:1}.pending-group{border-bottom:1px solid var(--line)}.pending-group-head,.pending-order-row{width:100%;border:0;background:#fff;padding:14px;text-align:left;display:flex;justify-content:space-between}.pending-group-head{background:#fff8f3}.pending-order-row{border-top:1px solid #eee}.pending-order-row span{display:grid;gap:4px}.pending-order-row span:last-child{text-align:right}.summary-row{display:flex;justify-content:space-between}.edit-thumb{width:54px;height:54px;border-radius:9px}.side-footer{margin-top:auto;padding:14px;border-top:1px solid var(--line);background:#fff;display:grid;gap:10px}.edit-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.edit-actions button{height:48px;border-radius:10px}"
c=c[:start]+card_css+c[end:]
assert '.pending-panel{width:31%' not in c and 'backdrop-filter:blur(10px)' in c
css.write_text(c,encoding='utf-8')

h=html.read_text(encoding='utf-8').replace('v16-5root-full-port-1','v16-5root-full-port-1.1')
html.write_text(h,encoding='utf-8')

note='''\n## V1.1 locked-card and quick-mode correction\n- All edit, pending-completion, quick, pending-order, health, status and display-setting cards use the same vertical span as the cart and a fixed 25% width.\n- Every side card uses one full-stage frosted scrim that blocks background interaction and supports tap-outside close.\n- Quick mode is independent from the quick-drink strip. When enabled, tapping any product immediately adds an incomplete line; required items are completed later in the pending area.\n- Cart edit uses the 25% side-card system; new-product detail retains the locked central 68/32 detail layout.\n- Pending card no longer overrides width to 31% or height to 50%.\n\n## Remaining verified gaps against 23df1f6 and a3a9ab0\n- Custom numeric keypad is still represented by the browser prompt rather than the locked in-app keypad.\n- Draft restore/list UI is not yet exposed even though draft persistence exists.\n- Quick-drink ordering/reordering UI is not yet restored.\n- Pending-order upper/lower independent scroll behavior is only partially restored.\n- Anchored arrow positioning from Master V1 is not yet restored for contextual cards.\n- Product-specific menu rules remain fixture-level and are not yet the complete production menu-rule engine.\n'''
text=status.read_text(encoding='utf-8')
if '## V1.1 locked-card and quick-mode correction' not in text:
    status.write_text(text+note,encoding='utf-8')

# lightweight regression checks
assert s.count("document.addEventListener('click'")==1
assert 'if(state.quickModeEnabled)quickAddProduct' in s
assert "state.card==='completion'" in s and "state.card==='edit'" in s
assert 'width:25%' in card_css and 'top:94px' in card_css and 'bottom:86px' in card_css
